//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.13 at 07:49:02 PM IST 
//


package org.acord.standards.life._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ApptCounty_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApptCounty_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}ApptCountyTC" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApptCounty_Type", propOrder = {
    "apptCountyTC"
})
public class ApptCountyType {

    @XmlElement(name = "ApptCountyTC")
    protected OLILUCOUNTY apptCountyTC;

    /**
     * Gets the value of the apptCountyTC property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUCOUNTY }
     *     
     */
    public OLILUCOUNTY getApptCountyTC() {
        return apptCountyTC;
    }

    /**
     * Sets the value of the apptCountyTC property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUCOUNTY }
     *     
     */
    public void setApptCountyTC(OLILUCOUNTY value) {
        this.apptCountyTC = value;
    }

}
