//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.13 at 07:49:02 PM IST 
//


package org.acord.standards.life._2;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AviationExp_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AviationExp_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}AviationExpKey" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}AviationExpSysKey" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}IFRInd" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}AviationType" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}StudentInd" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}AircraftType" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}AircraftSeries" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}JobAboardAircraft" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}FlyingPurpose" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}HighestQualificationLevel" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}HighestQualificationLevelDesc" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}ProposedQualificationLevelInd" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{http://ACORD.org/Standards/Life/2}DateOfQualification" minOccurs="0"/>
 *           &lt;element ref="{http://ACORD.org/Standards/Life/2}QualificationPartialDate" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}RenewalInd" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}ForeignFlightInd" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}GroundedInd" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}MedClassWaiverInd" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}RevokedInd" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}ExpectedForeignFlightYr" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}PreviousForeignFlightYr" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}MedExamClass" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}MedExamClassDesc" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}MedCertInd" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{http://ACORD.org/Standards/Life/2}MedCertOrigDate" minOccurs="0"/>
 *           &lt;element ref="{http://ACORD.org/Standards/Life/2}MedCertOrigPartialDate" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}NumberOfHoursLastYear" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}NumberOfHoursNextYear" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}NumOfHoursInstructPerYear" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}USCertificatedInd" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}AirmanCertificateInd" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}NumOfHoursLast2Year" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}TotalNumOfHoursFlown" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}FutureFlyingDiffPurposeInd" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}FutureFlyingDiffAircraftInd" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}SpecificJobAboardAircraft" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}NonDomesticAirCarrierInd" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}ValidAircraftInsuranceInd" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}CraftCertificateType" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}CraftCertificateTypeDesc" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}BranchOfService" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}Applicability" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}CertificateRatingType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}MedicalCertRestriction" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}CertificateCraftType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}Aircraft" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}OLifEExtension" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="DataRep" type="{http://ACORD.org/Standards/Life/2}DATAREP_TYPES" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AviationExp_Type", propOrder = {
    "aviationExpKey",
    "aviationExpSysKey",
    "ifrInd",
    "aviationType",
    "studentInd",
    "aircraftType",
    "aircraftSeries",
    "jobAboardAircraft",
    "flyingPurpose",
    "highestQualificationLevel",
    "highestQualificationLevelDesc",
    "proposedQualificationLevelInd",
    "dateOfQualification",
    "qualificationPartialDate",
    "renewalInd",
    "foreignFlightInd",
    "groundedInd",
    "medClassWaiverInd",
    "revokedInd",
    "expectedForeignFlightYr",
    "previousForeignFlightYr",
    "medExamClass",
    "medExamClassDesc",
    "medCertInd",
    "medCertOrigDate",
    "medCertOrigPartialDate",
    "numberOfHoursLastYear",
    "numberOfHoursNextYear",
    "numOfHoursInstructPerYear",
    "usCertificatedInd",
    "airmanCertificateInd",
    "numOfHoursLast2Year",
    "totalNumOfHoursFlown",
    "futureFlyingDiffPurposeInd",
    "futureFlyingDiffAircraftInd",
    "specificJobAboardAircraft",
    "nonDomesticAirCarrierInd",
    "validAircraftInsuranceInd",
    "craftCertificateType",
    "craftCertificateTypeDesc",
    "branchOfService",
    "applicability",
    "certificateRatingType",
    "medicalCertRestriction",
    "certificateCraftType",
    "aircraft",
    "oLifEExtension"
})
public class AviationExpType {

    @XmlElement(name = "AviationExpKey")
    protected PERSISTKEY aviationExpKey;
    @XmlElement(name = "AviationExpSysKey")
    protected List<SYSKEY> aviationExpSysKey;
    @XmlElement(name = "IFRInd")
    protected OLILUBOOLEAN ifrInd;
    @XmlElement(name = "AviationType")
    protected OLILUAVIATIONTYPE aviationType;
    @XmlElement(name = "StudentInd")
    protected OLILUBOOLEAN studentInd;
    @XmlElement(name = "AircraftType")
    protected OLILUAIRCRAFTTYPE aircraftType;
    @XmlElement(name = "AircraftSeries")
    protected String aircraftSeries;
    @XmlElement(name = "JobAboardAircraft")
    protected OLILUAIRCRAFTJOB jobAboardAircraft;
    @XmlElement(name = "FlyingPurpose")
    protected OLILUFLYINGPURPOSE flyingPurpose;
    @XmlElement(name = "HighestQualificationLevel")
    protected OLILUQUALLEVEL highestQualificationLevel;
    @XmlElement(name = "HighestQualificationLevelDesc")
    protected String highestQualificationLevelDesc;
    @XmlElement(name = "ProposedQualificationLevelInd")
    protected OLILUBOOLEAN proposedQualificationLevelInd;
    @XmlElement(name = "DateOfQualification")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateOfQualification;
    @XmlElement(name = "QualificationPartialDate")
    protected String qualificationPartialDate;
    @XmlElement(name = "RenewalInd")
    protected OLILUBOOLEAN renewalInd;
    @XmlElement(name = "ForeignFlightInd")
    protected OLILUBOOLEAN foreignFlightInd;
    @XmlElement(name = "GroundedInd")
    protected OLILUBOOLEAN groundedInd;
    @XmlElement(name = "MedClassWaiverInd")
    protected OLILUBOOLEAN medClassWaiverInd;
    @XmlElement(name = "RevokedInd")
    protected OLILUBOOLEAN revokedInd;
    @XmlElement(name = "ExpectedForeignFlightYr")
    @XmlSchemaType(name = "gYear")
    protected XMLGregorianCalendar expectedForeignFlightYr;
    @XmlElement(name = "PreviousForeignFlightYr")
    protected BigInteger previousForeignFlightYr;
    @XmlElement(name = "MedExamClass")
    protected OLILUMEDEXAM medExamClass;
    @XmlElement(name = "MedExamClassDesc")
    protected String medExamClassDesc;
    @XmlElement(name = "MedCertInd")
    protected OLILUBOOLEAN medCertInd;
    @XmlElement(name = "MedCertOrigDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar medCertOrigDate;
    @XmlElement(name = "MedCertOrigPartialDate")
    protected String medCertOrigPartialDate;
    @XmlElement(name = "NumberOfHoursLastYear")
    protected BigInteger numberOfHoursLastYear;
    @XmlElement(name = "NumberOfHoursNextYear")
    protected BigInteger numberOfHoursNextYear;
    @XmlElement(name = "NumOfHoursInstructPerYear")
    protected BigInteger numOfHoursInstructPerYear;
    @XmlElement(name = "USCertificatedInd")
    protected OLILUBOOLEAN usCertificatedInd;
    @XmlElement(name = "AirmanCertificateInd")
    protected OLILUBOOLEAN airmanCertificateInd;
    @XmlElement(name = "NumOfHoursLast2Year")
    protected BigInteger numOfHoursLast2Year;
    @XmlElement(name = "TotalNumOfHoursFlown")
    protected BigInteger totalNumOfHoursFlown;
    @XmlElement(name = "FutureFlyingDiffPurposeInd")
    protected OLILUBOOLEAN futureFlyingDiffPurposeInd;
    @XmlElement(name = "FutureFlyingDiffAircraftInd")
    protected OLILUBOOLEAN futureFlyingDiffAircraftInd;
    @XmlElement(name = "SpecificJobAboardAircraft")
    protected String specificJobAboardAircraft;
    @XmlElement(name = "NonDomesticAirCarrierInd")
    protected OLILUBOOLEAN nonDomesticAirCarrierInd;
    @XmlElement(name = "ValidAircraftInsuranceInd")
    protected OLILUBOOLEAN validAircraftInsuranceInd;
    @XmlElement(name = "CraftCertificateType")
    protected OLILUCRAFTCERT craftCertificateType;
    @XmlElement(name = "CraftCertificateTypeDesc")
    protected String craftCertificateTypeDesc;
    @XmlElement(name = "BranchOfService")
    protected OLILUMILITARYORGTYPE branchOfService;
    @XmlElement(name = "Applicability")
    protected OLILUAPPLICABILITY applicability;
    @XmlElement(name = "CertificateRatingType")
    protected List<CertificateRatingTypeType> certificateRatingType;
    @XmlElement(name = "MedicalCertRestriction")
    protected List<MedicalCertRestrictionType> medicalCertRestriction;
    @XmlElement(name = "CertificateCraftType")
    protected List<CertificateCraftTypeType> certificateCraftType;
    @XmlElement(name = "Aircraft")
    protected List<AircraftType> aircraft;
    @XmlElement(name = "OLifEExtension")
    protected List<OLifEExtensionType> oLifEExtension;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "DataRep")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dataRep;

    /**
     * Gets the value of the aviationExpKey property.
     * 
     * @return
     *     possible object is
     *     {@link PERSISTKEY }
     *     
     */
    public PERSISTKEY getAviationExpKey() {
        return aviationExpKey;
    }

    /**
     * Sets the value of the aviationExpKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link PERSISTKEY }
     *     
     */
    public void setAviationExpKey(PERSISTKEY value) {
        this.aviationExpKey = value;
    }

    /**
     * Gets the value of the aviationExpSysKey property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aviationExpSysKey property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAviationExpSysKey().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SYSKEY }
     * 
     * 
     */
    public List<SYSKEY> getAviationExpSysKey() {
        if (aviationExpSysKey == null) {
            aviationExpSysKey = new ArrayList<SYSKEY>();
        }
        return this.aviationExpSysKey;
    }

    /**
     * Gets the value of the ifrInd property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public OLILUBOOLEAN getIFRInd() {
        return ifrInd;
    }

    /**
     * Sets the value of the ifrInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public void setIFRInd(OLILUBOOLEAN value) {
        this.ifrInd = value;
    }

    /**
     * Gets the value of the aviationType property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUAVIATIONTYPE }
     *     
     */
    public OLILUAVIATIONTYPE getAviationType() {
        return aviationType;
    }

    /**
     * Sets the value of the aviationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUAVIATIONTYPE }
     *     
     */
    public void setAviationType(OLILUAVIATIONTYPE value) {
        this.aviationType = value;
    }

    /**
     * Gets the value of the studentInd property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public OLILUBOOLEAN getStudentInd() {
        return studentInd;
    }

    /**
     * Sets the value of the studentInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public void setStudentInd(OLILUBOOLEAN value) {
        this.studentInd = value;
    }

    /**
     * Gets the value of the aircraftType property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUAIRCRAFTTYPE }
     *     
     */
    public OLILUAIRCRAFTTYPE getAircraftType() {
        return aircraftType;
    }

    /**
     * Sets the value of the aircraftType property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUAIRCRAFTTYPE }
     *     
     */
    public void setAircraftType(OLILUAIRCRAFTTYPE value) {
        this.aircraftType = value;
    }

    /**
     * Gets the value of the aircraftSeries property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAircraftSeries() {
        return aircraftSeries;
    }

    /**
     * Sets the value of the aircraftSeries property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAircraftSeries(String value) {
        this.aircraftSeries = value;
    }

    /**
     * Gets the value of the jobAboardAircraft property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUAIRCRAFTJOB }
     *     
     */
    public OLILUAIRCRAFTJOB getJobAboardAircraft() {
        return jobAboardAircraft;
    }

    /**
     * Sets the value of the jobAboardAircraft property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUAIRCRAFTJOB }
     *     
     */
    public void setJobAboardAircraft(OLILUAIRCRAFTJOB value) {
        this.jobAboardAircraft = value;
    }

    /**
     * Gets the value of the flyingPurpose property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUFLYINGPURPOSE }
     *     
     */
    public OLILUFLYINGPURPOSE getFlyingPurpose() {
        return flyingPurpose;
    }

    /**
     * Sets the value of the flyingPurpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUFLYINGPURPOSE }
     *     
     */
    public void setFlyingPurpose(OLILUFLYINGPURPOSE value) {
        this.flyingPurpose = value;
    }

    /**
     * Gets the value of the highestQualificationLevel property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUQUALLEVEL }
     *     
     */
    public OLILUQUALLEVEL getHighestQualificationLevel() {
        return highestQualificationLevel;
    }

    /**
     * Sets the value of the highestQualificationLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUQUALLEVEL }
     *     
     */
    public void setHighestQualificationLevel(OLILUQUALLEVEL value) {
        this.highestQualificationLevel = value;
    }

    /**
     * Gets the value of the highestQualificationLevelDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHighestQualificationLevelDesc() {
        return highestQualificationLevelDesc;
    }

    /**
     * Sets the value of the highestQualificationLevelDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHighestQualificationLevelDesc(String value) {
        this.highestQualificationLevelDesc = value;
    }

    /**
     * Gets the value of the proposedQualificationLevelInd property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public OLILUBOOLEAN getProposedQualificationLevelInd() {
        return proposedQualificationLevelInd;
    }

    /**
     * Sets the value of the proposedQualificationLevelInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public void setProposedQualificationLevelInd(OLILUBOOLEAN value) {
        this.proposedQualificationLevelInd = value;
    }

    /**
     * Gets the value of the dateOfQualification property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateOfQualification() {
        return dateOfQualification;
    }

    /**
     * Sets the value of the dateOfQualification property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateOfQualification(XMLGregorianCalendar value) {
        this.dateOfQualification = value;
    }

    /**
     * Gets the value of the qualificationPartialDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQualificationPartialDate() {
        return qualificationPartialDate;
    }

    /**
     * Sets the value of the qualificationPartialDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQualificationPartialDate(String value) {
        this.qualificationPartialDate = value;
    }

    /**
     * Gets the value of the renewalInd property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public OLILUBOOLEAN getRenewalInd() {
        return renewalInd;
    }

    /**
     * Sets the value of the renewalInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public void setRenewalInd(OLILUBOOLEAN value) {
        this.renewalInd = value;
    }

    /**
     * Gets the value of the foreignFlightInd property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public OLILUBOOLEAN getForeignFlightInd() {
        return foreignFlightInd;
    }

    /**
     * Sets the value of the foreignFlightInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public void setForeignFlightInd(OLILUBOOLEAN value) {
        this.foreignFlightInd = value;
    }

    /**
     * Gets the value of the groundedInd property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public OLILUBOOLEAN getGroundedInd() {
        return groundedInd;
    }

    /**
     * Sets the value of the groundedInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public void setGroundedInd(OLILUBOOLEAN value) {
        this.groundedInd = value;
    }

    /**
     * Gets the value of the medClassWaiverInd property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public OLILUBOOLEAN getMedClassWaiverInd() {
        return medClassWaiverInd;
    }

    /**
     * Sets the value of the medClassWaiverInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public void setMedClassWaiverInd(OLILUBOOLEAN value) {
        this.medClassWaiverInd = value;
    }

    /**
     * Gets the value of the revokedInd property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public OLILUBOOLEAN getRevokedInd() {
        return revokedInd;
    }

    /**
     * Sets the value of the revokedInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public void setRevokedInd(OLILUBOOLEAN value) {
        this.revokedInd = value;
    }

    /**
     * Gets the value of the expectedForeignFlightYr property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpectedForeignFlightYr() {
        return expectedForeignFlightYr;
    }

    /**
     * Sets the value of the expectedForeignFlightYr property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpectedForeignFlightYr(XMLGregorianCalendar value) {
        this.expectedForeignFlightYr = value;
    }

    /**
     * Gets the value of the previousForeignFlightYr property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPreviousForeignFlightYr() {
        return previousForeignFlightYr;
    }

    /**
     * Sets the value of the previousForeignFlightYr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPreviousForeignFlightYr(BigInteger value) {
        this.previousForeignFlightYr = value;
    }

    /**
     * Gets the value of the medExamClass property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUMEDEXAM }
     *     
     */
    public OLILUMEDEXAM getMedExamClass() {
        return medExamClass;
    }

    /**
     * Sets the value of the medExamClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUMEDEXAM }
     *     
     */
    public void setMedExamClass(OLILUMEDEXAM value) {
        this.medExamClass = value;
    }

    /**
     * Gets the value of the medExamClassDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedExamClassDesc() {
        return medExamClassDesc;
    }

    /**
     * Sets the value of the medExamClassDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedExamClassDesc(String value) {
        this.medExamClassDesc = value;
    }

    /**
     * Gets the value of the medCertInd property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public OLILUBOOLEAN getMedCertInd() {
        return medCertInd;
    }

    /**
     * Sets the value of the medCertInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public void setMedCertInd(OLILUBOOLEAN value) {
        this.medCertInd = value;
    }

    /**
     * Gets the value of the medCertOrigDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMedCertOrigDate() {
        return medCertOrigDate;
    }

    /**
     * Sets the value of the medCertOrigDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMedCertOrigDate(XMLGregorianCalendar value) {
        this.medCertOrigDate = value;
    }

    /**
     * Gets the value of the medCertOrigPartialDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedCertOrigPartialDate() {
        return medCertOrigPartialDate;
    }

    /**
     * Sets the value of the medCertOrigPartialDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedCertOrigPartialDate(String value) {
        this.medCertOrigPartialDate = value;
    }

    /**
     * Gets the value of the numberOfHoursLastYear property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfHoursLastYear() {
        return numberOfHoursLastYear;
    }

    /**
     * Sets the value of the numberOfHoursLastYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfHoursLastYear(BigInteger value) {
        this.numberOfHoursLastYear = value;
    }

    /**
     * Gets the value of the numberOfHoursNextYear property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfHoursNextYear() {
        return numberOfHoursNextYear;
    }

    /**
     * Sets the value of the numberOfHoursNextYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfHoursNextYear(BigInteger value) {
        this.numberOfHoursNextYear = value;
    }

    /**
     * Gets the value of the numOfHoursInstructPerYear property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumOfHoursInstructPerYear() {
        return numOfHoursInstructPerYear;
    }

    /**
     * Sets the value of the numOfHoursInstructPerYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumOfHoursInstructPerYear(BigInteger value) {
        this.numOfHoursInstructPerYear = value;
    }

    /**
     * Gets the value of the usCertificatedInd property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public OLILUBOOLEAN getUSCertificatedInd() {
        return usCertificatedInd;
    }

    /**
     * Sets the value of the usCertificatedInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public void setUSCertificatedInd(OLILUBOOLEAN value) {
        this.usCertificatedInd = value;
    }

    /**
     * Gets the value of the airmanCertificateInd property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public OLILUBOOLEAN getAirmanCertificateInd() {
        return airmanCertificateInd;
    }

    /**
     * Sets the value of the airmanCertificateInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public void setAirmanCertificateInd(OLILUBOOLEAN value) {
        this.airmanCertificateInd = value;
    }

    /**
     * Gets the value of the numOfHoursLast2Year property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumOfHoursLast2Year() {
        return numOfHoursLast2Year;
    }

    /**
     * Sets the value of the numOfHoursLast2Year property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumOfHoursLast2Year(BigInteger value) {
        this.numOfHoursLast2Year = value;
    }

    /**
     * Gets the value of the totalNumOfHoursFlown property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalNumOfHoursFlown() {
        return totalNumOfHoursFlown;
    }

    /**
     * Sets the value of the totalNumOfHoursFlown property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalNumOfHoursFlown(BigInteger value) {
        this.totalNumOfHoursFlown = value;
    }

    /**
     * Gets the value of the futureFlyingDiffPurposeInd property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public OLILUBOOLEAN getFutureFlyingDiffPurposeInd() {
        return futureFlyingDiffPurposeInd;
    }

    /**
     * Sets the value of the futureFlyingDiffPurposeInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public void setFutureFlyingDiffPurposeInd(OLILUBOOLEAN value) {
        this.futureFlyingDiffPurposeInd = value;
    }

    /**
     * Gets the value of the futureFlyingDiffAircraftInd property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public OLILUBOOLEAN getFutureFlyingDiffAircraftInd() {
        return futureFlyingDiffAircraftInd;
    }

    /**
     * Sets the value of the futureFlyingDiffAircraftInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public void setFutureFlyingDiffAircraftInd(OLILUBOOLEAN value) {
        this.futureFlyingDiffAircraftInd = value;
    }

    /**
     * Gets the value of the specificJobAboardAircraft property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecificJobAboardAircraft() {
        return specificJobAboardAircraft;
    }

    /**
     * Sets the value of the specificJobAboardAircraft property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecificJobAboardAircraft(String value) {
        this.specificJobAboardAircraft = value;
    }

    /**
     * Gets the value of the nonDomesticAirCarrierInd property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public OLILUBOOLEAN getNonDomesticAirCarrierInd() {
        return nonDomesticAirCarrierInd;
    }

    /**
     * Sets the value of the nonDomesticAirCarrierInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public void setNonDomesticAirCarrierInd(OLILUBOOLEAN value) {
        this.nonDomesticAirCarrierInd = value;
    }

    /**
     * Gets the value of the validAircraftInsuranceInd property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public OLILUBOOLEAN getValidAircraftInsuranceInd() {
        return validAircraftInsuranceInd;
    }

    /**
     * Sets the value of the validAircraftInsuranceInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public void setValidAircraftInsuranceInd(OLILUBOOLEAN value) {
        this.validAircraftInsuranceInd = value;
    }

    /**
     * Gets the value of the craftCertificateType property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUCRAFTCERT }
     *     
     */
    public OLILUCRAFTCERT getCraftCertificateType() {
        return craftCertificateType;
    }

    /**
     * Sets the value of the craftCertificateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUCRAFTCERT }
     *     
     */
    public void setCraftCertificateType(OLILUCRAFTCERT value) {
        this.craftCertificateType = value;
    }

    /**
     * Gets the value of the craftCertificateTypeDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCraftCertificateTypeDesc() {
        return craftCertificateTypeDesc;
    }

    /**
     * Sets the value of the craftCertificateTypeDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCraftCertificateTypeDesc(String value) {
        this.craftCertificateTypeDesc = value;
    }

    /**
     * Gets the value of the branchOfService property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUMILITARYORGTYPE }
     *     
     */
    public OLILUMILITARYORGTYPE getBranchOfService() {
        return branchOfService;
    }

    /**
     * Sets the value of the branchOfService property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUMILITARYORGTYPE }
     *     
     */
    public void setBranchOfService(OLILUMILITARYORGTYPE value) {
        this.branchOfService = value;
    }

    /**
     * Gets the value of the applicability property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUAPPLICABILITY }
     *     
     */
    public OLILUAPPLICABILITY getApplicability() {
        return applicability;
    }

    /**
     * Sets the value of the applicability property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUAPPLICABILITY }
     *     
     */
    public void setApplicability(OLILUAPPLICABILITY value) {
        this.applicability = value;
    }

    /**
     * Gets the value of the certificateRatingType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the certificateRatingType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCertificateRatingType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CertificateRatingTypeType }
     * 
     * 
     */
    public List<CertificateRatingTypeType> getCertificateRatingType() {
        if (certificateRatingType == null) {
            certificateRatingType = new ArrayList<CertificateRatingTypeType>();
        }
        return this.certificateRatingType;
    }

    /**
     * Gets the value of the medicalCertRestriction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the medicalCertRestriction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMedicalCertRestriction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MedicalCertRestrictionType }
     * 
     * 
     */
    public List<MedicalCertRestrictionType> getMedicalCertRestriction() {
        if (medicalCertRestriction == null) {
            medicalCertRestriction = new ArrayList<MedicalCertRestrictionType>();
        }
        return this.medicalCertRestriction;
    }

    /**
     * Gets the value of the certificateCraftType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the certificateCraftType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCertificateCraftType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CertificateCraftTypeType }
     * 
     * 
     */
    public List<CertificateCraftTypeType> getCertificateCraftType() {
        if (certificateCraftType == null) {
            certificateCraftType = new ArrayList<CertificateCraftTypeType>();
        }
        return this.certificateCraftType;
    }

    /**
     * Gets the value of the aircraft property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aircraft property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAircraft().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AircraftType }
     * 
     * 
     */
    public List<AircraftType> getAircraft() {
        if (aircraft == null) {
            aircraft = new ArrayList<AircraftType>();
        }
        return this.aircraft;
    }

    /**
     * Gets the value of the oLifEExtension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the oLifEExtension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOLifEExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OLifEExtensionType }
     * 
     * 
     */
    public List<OLifEExtensionType> getOLifEExtension() {
        if (oLifEExtension == null) {
            oLifEExtension = new ArrayList<OLifEExtensionType>();
        }
        return this.oLifEExtension;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the dataRep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataRep() {
        return dataRep;
    }

    /**
     * Sets the value of the dataRep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataRep(String value) {
        this.dataRep = value;
    }

}
