//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.13 at 07:49:02 PM IST 
//


package org.acord.standards.life._2;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Banking_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Banking_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}BankingKey" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}BankingSysKey" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}CreditDebitType" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}BankAcctType" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}CreditCardType" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}CreditCardTypeDesc" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}CreditCardExpDate" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}AccountNumber" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}RoutingNum" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}InstitutionNumber" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}TransitNumber" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}AcctHolderName" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}BankName" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}BankBranchName" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}CardVerificationNum" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}SurrenderChargeAmt" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}AccountToken" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}AccountVerificationNumber" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}AuthorizedSignatory" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}PriorName" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}OLifEExtension" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="FinancialInstitutionPartyID" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="AppliesToPartyID" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="MailingAddressID" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="DataRep" type="{http://ACORD.org/Standards/Life/2}DATAREP_TYPES" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Banking_Type", propOrder = {
    "bankingKey",
    "bankingSysKey",
    "creditDebitType",
    "bankAcctType",
    "creditCardType",
    "creditCardTypeDesc",
    "creditCardExpDate",
    "accountNumber",
    "routingNum",
    "institutionNumber",
    "transitNumber",
    "acctHolderName",
    "bankName",
    "bankBranchName",
    "cardVerificationNum",
    "surrenderChargeAmt",
    "accountToken",
    "accountVerificationNumber",
    "authorizedSignatory",
    "priorName",
    "oLifEExtension"
})
public class BankingType {

    @XmlElement(name = "BankingKey")
    protected PERSISTKEY bankingKey;
    @XmlElement(name = "BankingSysKey")
    protected List<SYSKEY> bankingSysKey;
    @XmlElement(name = "CreditDebitType")
    protected OLILUACCTDBCRTYPE creditDebitType;
    @XmlElement(name = "BankAcctType")
    protected OLILUBANKACCTTYPE bankAcctType;
    @XmlElement(name = "CreditCardType")
    protected OLILUCREDCARDTYPE creditCardType;
    @XmlElement(name = "CreditCardTypeDesc")
    protected String creditCardTypeDesc;
    @XmlElement(name = "CreditCardExpDate")
    @XmlSchemaType(name = "gYearMonth")
    protected XMLGregorianCalendar creditCardExpDate;
    @XmlElement(name = "AccountNumber")
    protected String accountNumber;
    @XmlElement(name = "RoutingNum")
    protected String routingNum;
    @XmlElement(name = "InstitutionNumber")
    protected String institutionNumber;
    @XmlElement(name = "TransitNumber")
    protected String transitNumber;
    @XmlElement(name = "AcctHolderName")
    protected String acctHolderName;
    @XmlElement(name = "BankName")
    protected String bankName;
    @XmlElement(name = "BankBranchName")
    protected String bankBranchName;
    @XmlElement(name = "CardVerificationNum")
    protected String cardVerificationNum;
    @XmlElement(name = "SurrenderChargeAmt")
    protected BigDecimal surrenderChargeAmt;
    @XmlElement(name = "AccountToken")
    protected String accountToken;
    @XmlElement(name = "AccountVerificationNumber")
    protected String accountVerificationNumber;
    @XmlElement(name = "AuthorizedSignatory")
    protected List<AuthorizedSignatoryType> authorizedSignatory;
    @XmlElement(name = "PriorName")
    protected PriorNameType priorName;
    @XmlElement(name = "OLifEExtension")
    protected List<OLifEExtensionType> oLifEExtension;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "FinancialInstitutionPartyID")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object financialInstitutionPartyID;
    @XmlAttribute(name = "AppliesToPartyID")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object appliesToPartyID;
    @XmlAttribute(name = "MailingAddressID")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object mailingAddressID;
    @XmlAttribute(name = "DataRep")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dataRep;

    /**
     * Gets the value of the bankingKey property.
     * 
     * @return
     *     possible object is
     *     {@link PERSISTKEY }
     *     
     */
    public PERSISTKEY getBankingKey() {
        return bankingKey;
    }

    /**
     * Sets the value of the bankingKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link PERSISTKEY }
     *     
     */
    public void setBankingKey(PERSISTKEY value) {
        this.bankingKey = value;
    }

    /**
     * Gets the value of the bankingSysKey property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bankingSysKey property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBankingSysKey().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SYSKEY }
     * 
     * 
     */
    public List<SYSKEY> getBankingSysKey() {
        if (bankingSysKey == null) {
            bankingSysKey = new ArrayList<SYSKEY>();
        }
        return this.bankingSysKey;
    }

    /**
     * Gets the value of the creditDebitType property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUACCTDBCRTYPE }
     *     
     */
    public OLILUACCTDBCRTYPE getCreditDebitType() {
        return creditDebitType;
    }

    /**
     * Sets the value of the creditDebitType property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUACCTDBCRTYPE }
     *     
     */
    public void setCreditDebitType(OLILUACCTDBCRTYPE value) {
        this.creditDebitType = value;
    }

    /**
     * Gets the value of the bankAcctType property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUBANKACCTTYPE }
     *     
     */
    public OLILUBANKACCTTYPE getBankAcctType() {
        return bankAcctType;
    }

    /**
     * Sets the value of the bankAcctType property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUBANKACCTTYPE }
     *     
     */
    public void setBankAcctType(OLILUBANKACCTTYPE value) {
        this.bankAcctType = value;
    }

    /**
     * Gets the value of the creditCardType property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUCREDCARDTYPE }
     *     
     */
    public OLILUCREDCARDTYPE getCreditCardType() {
        return creditCardType;
    }

    /**
     * Sets the value of the creditCardType property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUCREDCARDTYPE }
     *     
     */
    public void setCreditCardType(OLILUCREDCARDTYPE value) {
        this.creditCardType = value;
    }

    /**
     * Gets the value of the creditCardTypeDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditCardTypeDesc() {
        return creditCardTypeDesc;
    }

    /**
     * Sets the value of the creditCardTypeDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditCardTypeDesc(String value) {
        this.creditCardTypeDesc = value;
    }

    /**
     * Gets the value of the creditCardExpDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreditCardExpDate() {
        return creditCardExpDate;
    }

    /**
     * Sets the value of the creditCardExpDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreditCardExpDate(XMLGregorianCalendar value) {
        this.creditCardExpDate = value;
    }

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNumber(String value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the routingNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoutingNum() {
        return routingNum;
    }

    /**
     * Sets the value of the routingNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoutingNum(String value) {
        this.routingNum = value;
    }

    /**
     * Gets the value of the institutionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstitutionNumber() {
        return institutionNumber;
    }

    /**
     * Sets the value of the institutionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstitutionNumber(String value) {
        this.institutionNumber = value;
    }

    /**
     * Gets the value of the transitNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransitNumber() {
        return transitNumber;
    }

    /**
     * Sets the value of the transitNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransitNumber(String value) {
        this.transitNumber = value;
    }

    /**
     * Gets the value of the acctHolderName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctHolderName() {
        return acctHolderName;
    }

    /**
     * Sets the value of the acctHolderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctHolderName(String value) {
        this.acctHolderName = value;
    }

    /**
     * Gets the value of the bankName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * Sets the value of the bankName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankName(String value) {
        this.bankName = value;
    }

    /**
     * Gets the value of the bankBranchName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankBranchName() {
        return bankBranchName;
    }

    /**
     * Sets the value of the bankBranchName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankBranchName(String value) {
        this.bankBranchName = value;
    }

    /**
     * Gets the value of the cardVerificationNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardVerificationNum() {
        return cardVerificationNum;
    }

    /**
     * Sets the value of the cardVerificationNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardVerificationNum(String value) {
        this.cardVerificationNum = value;
    }

    /**
     * Gets the value of the surrenderChargeAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSurrenderChargeAmt() {
        return surrenderChargeAmt;
    }

    /**
     * Sets the value of the surrenderChargeAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSurrenderChargeAmt(BigDecimal value) {
        this.surrenderChargeAmt = value;
    }

    /**
     * Gets the value of the accountToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountToken() {
        return accountToken;
    }

    /**
     * Sets the value of the accountToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountToken(String value) {
        this.accountToken = value;
    }

    /**
     * Gets the value of the accountVerificationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountVerificationNumber() {
        return accountVerificationNumber;
    }

    /**
     * Sets the value of the accountVerificationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountVerificationNumber(String value) {
        this.accountVerificationNumber = value;
    }

    /**
     * Gets the value of the authorizedSignatory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the authorizedSignatory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuthorizedSignatory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AuthorizedSignatoryType }
     * 
     * 
     */
    public List<AuthorizedSignatoryType> getAuthorizedSignatory() {
        if (authorizedSignatory == null) {
            authorizedSignatory = new ArrayList<AuthorizedSignatoryType>();
        }
        return this.authorizedSignatory;
    }

    /**
     * Gets the value of the priorName property.
     * 
     * @return
     *     possible object is
     *     {@link PriorNameType }
     *     
     */
    public PriorNameType getPriorName() {
        return priorName;
    }

    /**
     * Sets the value of the priorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriorNameType }
     *     
     */
    public void setPriorName(PriorNameType value) {
        this.priorName = value;
    }

    /**
     * Gets the value of the oLifEExtension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the oLifEExtension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOLifEExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OLifEExtensionType }
     * 
     * 
     */
    public List<OLifEExtensionType> getOLifEExtension() {
        if (oLifEExtension == null) {
            oLifEExtension = new ArrayList<OLifEExtensionType>();
        }
        return this.oLifEExtension;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the financialInstitutionPartyID property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getFinancialInstitutionPartyID() {
        return financialInstitutionPartyID;
    }

    /**
     * Sets the value of the financialInstitutionPartyID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setFinancialInstitutionPartyID(Object value) {
        this.financialInstitutionPartyID = value;
    }

    /**
     * Gets the value of the appliesToPartyID property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAppliesToPartyID() {
        return appliesToPartyID;
    }

    /**
     * Sets the value of the appliesToPartyID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAppliesToPartyID(Object value) {
        this.appliesToPartyID = value;
    }

    /**
     * Gets the value of the mailingAddressID property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getMailingAddressID() {
        return mailingAddressID;
    }

    /**
     * Sets the value of the mailingAddressID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setMailingAddressID(Object value) {
        this.mailingAddressID = value;
    }

    /**
     * Gets the value of the dataRep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataRep() {
        return dataRep;
    }

    /**
     * Sets the value of the dataRep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataRep(String value) {
        this.dataRep = value;
    }

}
