//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.13 at 07:49:02 PM IST 
//


package org.acord.standards.life._2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for CardiacMurmur_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CardiacMurmur_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}CardiacMurmurKey" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}CardiacMurmurSysKey" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}ConditionInd" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}TransmittedInd" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}IntensityGradeTC" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}LocationTC" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}QualityTC" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}TimingTC" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}AfterExerciseDesc" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}OLifEExtension" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="PartyID" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="DataRep" type="{http://ACORD.org/Standards/Life/2}DATAREP_TYPES" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CardiacMurmur_Type", propOrder = {
    "cardiacMurmurKey",
    "cardiacMurmurSysKey",
    "conditionInd",
    "transmittedInd",
    "intensityGradeTC",
    "locationTC",
    "qualityTC",
    "timingTC",
    "afterExerciseDesc",
    "oLifEExtension"
})
public class CardiacMurmurType {

    @XmlElement(name = "CardiacMurmurKey")
    protected PERSISTKEY cardiacMurmurKey;
    @XmlElement(name = "CardiacMurmurSysKey")
    protected List<SYSKEY> cardiacMurmurSysKey;
    @XmlElement(name = "ConditionInd")
    protected OLILUBOOLEAN conditionInd;
    @XmlElement(name = "TransmittedInd")
    protected OLILUBOOLEAN transmittedInd;
    @XmlElement(name = "IntensityGradeTC")
    protected OLILUCARDIACINT intensityGradeTC;
    @XmlElement(name = "LocationTC")
    protected OLILUCARDIACLOC locationTC;
    @XmlElement(name = "QualityTC")
    protected OLILUCARDIACQUAL qualityTC;
    @XmlElement(name = "TimingTC")
    protected OLILUCARDIACTIM timingTC;
    @XmlElement(name = "AfterExerciseDesc")
    protected String afterExerciseDesc;
    @XmlElement(name = "OLifEExtension")
    protected List<OLifEExtensionType> oLifEExtension;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "PartyID")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object partyID;
    @XmlAttribute(name = "DataRep")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dataRep;

    /**
     * Gets the value of the cardiacMurmurKey property.
     * 
     * @return
     *     possible object is
     *     {@link PERSISTKEY }
     *     
     */
    public PERSISTKEY getCardiacMurmurKey() {
        return cardiacMurmurKey;
    }

    /**
     * Sets the value of the cardiacMurmurKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link PERSISTKEY }
     *     
     */
    public void setCardiacMurmurKey(PERSISTKEY value) {
        this.cardiacMurmurKey = value;
    }

    /**
     * Gets the value of the cardiacMurmurSysKey property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cardiacMurmurSysKey property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCardiacMurmurSysKey().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SYSKEY }
     * 
     * 
     */
    public List<SYSKEY> getCardiacMurmurSysKey() {
        if (cardiacMurmurSysKey == null) {
            cardiacMurmurSysKey = new ArrayList<SYSKEY>();
        }
        return this.cardiacMurmurSysKey;
    }

    /**
     * Gets the value of the conditionInd property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public OLILUBOOLEAN getConditionInd() {
        return conditionInd;
    }

    /**
     * Sets the value of the conditionInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public void setConditionInd(OLILUBOOLEAN value) {
        this.conditionInd = value;
    }

    /**
     * Gets the value of the transmittedInd property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public OLILUBOOLEAN getTransmittedInd() {
        return transmittedInd;
    }

    /**
     * Sets the value of the transmittedInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public void setTransmittedInd(OLILUBOOLEAN value) {
        this.transmittedInd = value;
    }

    /**
     * Gets the value of the intensityGradeTC property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUCARDIACINT }
     *     
     */
    public OLILUCARDIACINT getIntensityGradeTC() {
        return intensityGradeTC;
    }

    /**
     * Sets the value of the intensityGradeTC property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUCARDIACINT }
     *     
     */
    public void setIntensityGradeTC(OLILUCARDIACINT value) {
        this.intensityGradeTC = value;
    }

    /**
     * Gets the value of the locationTC property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUCARDIACLOC }
     *     
     */
    public OLILUCARDIACLOC getLocationTC() {
        return locationTC;
    }

    /**
     * Sets the value of the locationTC property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUCARDIACLOC }
     *     
     */
    public void setLocationTC(OLILUCARDIACLOC value) {
        this.locationTC = value;
    }

    /**
     * Gets the value of the qualityTC property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUCARDIACQUAL }
     *     
     */
    public OLILUCARDIACQUAL getQualityTC() {
        return qualityTC;
    }

    /**
     * Sets the value of the qualityTC property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUCARDIACQUAL }
     *     
     */
    public void setQualityTC(OLILUCARDIACQUAL value) {
        this.qualityTC = value;
    }

    /**
     * Gets the value of the timingTC property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUCARDIACTIM }
     *     
     */
    public OLILUCARDIACTIM getTimingTC() {
        return timingTC;
    }

    /**
     * Sets the value of the timingTC property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUCARDIACTIM }
     *     
     */
    public void setTimingTC(OLILUCARDIACTIM value) {
        this.timingTC = value;
    }

    /**
     * Gets the value of the afterExerciseDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAfterExerciseDesc() {
        return afterExerciseDesc;
    }

    /**
     * Sets the value of the afterExerciseDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAfterExerciseDesc(String value) {
        this.afterExerciseDesc = value;
    }

    /**
     * Gets the value of the oLifEExtension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the oLifEExtension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOLifEExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OLifEExtensionType }
     * 
     * 
     */
    public List<OLifEExtensionType> getOLifEExtension() {
        if (oLifEExtension == null) {
            oLifEExtension = new ArrayList<OLifEExtensionType>();
        }
        return this.oLifEExtension;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the partyID property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPartyID() {
        return partyID;
    }

    /**
     * Sets the value of the partyID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPartyID(Object value) {
        this.partyID = value;
    }

    /**
     * Gets the value of the dataRep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataRep() {
        return dataRep;
    }

    /**
     * Sets the value of the dataRep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataRep(String value) {
        this.dataRep = value;
    }

}
