//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.13 at 07:49:02 PM IST 
//


package org.acord.standards.life._2;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ClaimEstimate_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClaimEstimate_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}ClaimEstimateKey" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}ClaimEstimateSysKey" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}EstType" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}EstCost" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}EstRecoveryDate" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}EstDurationValue" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}FulfilledDate" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}ActivityDetails" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}DurationUnitMeasure" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}OLifEExtension" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="DataRep" type="{http://ACORD.org/Standards/Life/2}DATAREP_TYPES" />
 *       &lt;attribute name="ProviderPartyID" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClaimEstimate_Type", propOrder = {
    "claimEstimateKey",
    "claimEstimateSysKey",
    "estType",
    "estCost",
    "estRecoveryDate",
    "estDurationValue",
    "fulfilledDate",
    "activityDetails",
    "durationUnitMeasure",
    "oLifEExtension"
})
public class ClaimEstimateType {

    @XmlElement(name = "ClaimEstimateKey")
    protected PERSISTKEY claimEstimateKey;
    @XmlElement(name = "ClaimEstimateSysKey")
    protected List<SYSKEY> claimEstimateSysKey;
    @XmlElement(name = "EstType")
    protected OLILUESTTYPE estType;
    @XmlElement(name = "EstCost")
    protected BigDecimal estCost;
    @XmlElement(name = "EstRecoveryDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar estRecoveryDate;
    @XmlElement(name = "EstDurationValue")
    protected BigInteger estDurationValue;
    @XmlElement(name = "FulfilledDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fulfilledDate;
    @XmlElement(name = "ActivityDetails")
    protected String activityDetails;
    @XmlElement(name = "DurationUnitMeasure")
    protected OLILUMEASUNITS durationUnitMeasure;
    @XmlElement(name = "OLifEExtension")
    protected List<OLifEExtensionType> oLifEExtension;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "DataRep")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dataRep;
    @XmlAttribute(name = "ProviderPartyID")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object providerPartyID;

    /**
     * Gets the value of the claimEstimateKey property.
     * 
     * @return
     *     possible object is
     *     {@link PERSISTKEY }
     *     
     */
    public PERSISTKEY getClaimEstimateKey() {
        return claimEstimateKey;
    }

    /**
     * Sets the value of the claimEstimateKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link PERSISTKEY }
     *     
     */
    public void setClaimEstimateKey(PERSISTKEY value) {
        this.claimEstimateKey = value;
    }

    /**
     * Gets the value of the claimEstimateSysKey property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the claimEstimateSysKey property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClaimEstimateSysKey().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SYSKEY }
     * 
     * 
     */
    public List<SYSKEY> getClaimEstimateSysKey() {
        if (claimEstimateSysKey == null) {
            claimEstimateSysKey = new ArrayList<SYSKEY>();
        }
        return this.claimEstimateSysKey;
    }

    /**
     * Gets the value of the estType property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUESTTYPE }
     *     
     */
    public OLILUESTTYPE getEstType() {
        return estType;
    }

    /**
     * Sets the value of the estType property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUESTTYPE }
     *     
     */
    public void setEstType(OLILUESTTYPE value) {
        this.estType = value;
    }

    /**
     * Gets the value of the estCost property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEstCost() {
        return estCost;
    }

    /**
     * Sets the value of the estCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEstCost(BigDecimal value) {
        this.estCost = value;
    }

    /**
     * Gets the value of the estRecoveryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEstRecoveryDate() {
        return estRecoveryDate;
    }

    /**
     * Sets the value of the estRecoveryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEstRecoveryDate(XMLGregorianCalendar value) {
        this.estRecoveryDate = value;
    }

    /**
     * Gets the value of the estDurationValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEstDurationValue() {
        return estDurationValue;
    }

    /**
     * Sets the value of the estDurationValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEstDurationValue(BigInteger value) {
        this.estDurationValue = value;
    }

    /**
     * Gets the value of the fulfilledDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFulfilledDate() {
        return fulfilledDate;
    }

    /**
     * Sets the value of the fulfilledDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFulfilledDate(XMLGregorianCalendar value) {
        this.fulfilledDate = value;
    }

    /**
     * Gets the value of the activityDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivityDetails() {
        return activityDetails;
    }

    /**
     * Sets the value of the activityDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivityDetails(String value) {
        this.activityDetails = value;
    }

    /**
     * Gets the value of the durationUnitMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUMEASUNITS }
     *     
     */
    public OLILUMEASUNITS getDurationUnitMeasure() {
        return durationUnitMeasure;
    }

    /**
     * Sets the value of the durationUnitMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUMEASUNITS }
     *     
     */
    public void setDurationUnitMeasure(OLILUMEASUNITS value) {
        this.durationUnitMeasure = value;
    }

    /**
     * Gets the value of the oLifEExtension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the oLifEExtension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOLifEExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OLifEExtensionType }
     * 
     * 
     */
    public List<OLifEExtensionType> getOLifEExtension() {
        if (oLifEExtension == null) {
            oLifEExtension = new ArrayList<OLifEExtensionType>();
        }
        return this.oLifEExtension;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the dataRep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataRep() {
        return dataRep;
    }

    /**
     * Sets the value of the dataRep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataRep(String value) {
        this.dataRep = value;
    }

    /**
     * Gets the value of the providerPartyID property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getProviderPartyID() {
        return providerPartyID;
    }

    /**
     * Sets the value of the providerPartyID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setProviderPartyID(Object value) {
        this.providerPartyID = value;
    }

}
