//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.13 at 07:49:02 PM IST 
//


package org.acord.standards.life._2;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for DivePurpose_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DivePurpose_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}DivePurposeKey" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}DivePurposeSysKey" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}DivePurposeType" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}DivePurposeDesc" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}AvgDepthLastYear" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}AvgDepthNextYear" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}AvgMinuteLastYear" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}AvgMinuteNextYear" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}DivingLocations" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}DivingEquipment" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}EquipmentServicedInd" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}OLifEExtension" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="DataRep" type="{http://ACORD.org/Standards/Life/2}DATAREP_TYPES" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DivePurpose_Type", propOrder = {
    "divePurposeKey",
    "divePurposeSysKey",
    "divePurposeType",
    "divePurposeDesc",
    "avgDepthLastYear",
    "avgDepthNextYear",
    "avgMinuteLastYear",
    "avgMinuteNextYear",
    "divingLocations",
    "divingEquipment",
    "equipmentServicedInd",
    "oLifEExtension"
})
public class DivePurposeType {

    @XmlElement(name = "DivePurposeKey")
    protected PERSISTKEY divePurposeKey;
    @XmlElement(name = "DivePurposeSysKey")
    protected List<SYSKEY> divePurposeSysKey;
    @XmlElement(name = "DivePurposeType")
    protected OLILUDIVEPURPOSE divePurposeType;
    @XmlElement(name = "DivePurposeDesc")
    protected String divePurposeDesc;
    @XmlElement(name = "AvgDepthLastYear")
    protected BigInteger avgDepthLastYear;
    @XmlElement(name = "AvgDepthNextYear")
    protected BigInteger avgDepthNextYear;
    @XmlElement(name = "AvgMinuteLastYear")
    protected BigInteger avgMinuteLastYear;
    @XmlElement(name = "AvgMinuteNextYear")
    protected BigInteger avgMinuteNextYear;
    @XmlElement(name = "DivingLocations")
    protected String divingLocations;
    @XmlElement(name = "DivingEquipment")
    protected String divingEquipment;
    @XmlElement(name = "EquipmentServicedInd")
    protected OLILUBOOLEAN equipmentServicedInd;
    @XmlElement(name = "OLifEExtension")
    protected List<OLifEExtensionType> oLifEExtension;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "DataRep")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dataRep;

    /**
     * Gets the value of the divePurposeKey property.
     * 
     * @return
     *     possible object is
     *     {@link PERSISTKEY }
     *     
     */
    public PERSISTKEY getDivePurposeKey() {
        return divePurposeKey;
    }

    /**
     * Sets the value of the divePurposeKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link PERSISTKEY }
     *     
     */
    public void setDivePurposeKey(PERSISTKEY value) {
        this.divePurposeKey = value;
    }

    /**
     * Gets the value of the divePurposeSysKey property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the divePurposeSysKey property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDivePurposeSysKey().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SYSKEY }
     * 
     * 
     */
    public List<SYSKEY> getDivePurposeSysKey() {
        if (divePurposeSysKey == null) {
            divePurposeSysKey = new ArrayList<SYSKEY>();
        }
        return this.divePurposeSysKey;
    }

    /**
     * Gets the value of the divePurposeType property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUDIVEPURPOSE }
     *     
     */
    public OLILUDIVEPURPOSE getDivePurposeType() {
        return divePurposeType;
    }

    /**
     * Sets the value of the divePurposeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUDIVEPURPOSE }
     *     
     */
    public void setDivePurposeType(OLILUDIVEPURPOSE value) {
        this.divePurposeType = value;
    }

    /**
     * Gets the value of the divePurposeDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDivePurposeDesc() {
        return divePurposeDesc;
    }

    /**
     * Sets the value of the divePurposeDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDivePurposeDesc(String value) {
        this.divePurposeDesc = value;
    }

    /**
     * Gets the value of the avgDepthLastYear property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAvgDepthLastYear() {
        return avgDepthLastYear;
    }

    /**
     * Sets the value of the avgDepthLastYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAvgDepthLastYear(BigInteger value) {
        this.avgDepthLastYear = value;
    }

    /**
     * Gets the value of the avgDepthNextYear property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAvgDepthNextYear() {
        return avgDepthNextYear;
    }

    /**
     * Sets the value of the avgDepthNextYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAvgDepthNextYear(BigInteger value) {
        this.avgDepthNextYear = value;
    }

    /**
     * Gets the value of the avgMinuteLastYear property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAvgMinuteLastYear() {
        return avgMinuteLastYear;
    }

    /**
     * Sets the value of the avgMinuteLastYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAvgMinuteLastYear(BigInteger value) {
        this.avgMinuteLastYear = value;
    }

    /**
     * Gets the value of the avgMinuteNextYear property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAvgMinuteNextYear() {
        return avgMinuteNextYear;
    }

    /**
     * Sets the value of the avgMinuteNextYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAvgMinuteNextYear(BigInteger value) {
        this.avgMinuteNextYear = value;
    }

    /**
     * Gets the value of the divingLocations property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDivingLocations() {
        return divingLocations;
    }

    /**
     * Sets the value of the divingLocations property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDivingLocations(String value) {
        this.divingLocations = value;
    }

    /**
     * Gets the value of the divingEquipment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDivingEquipment() {
        return divingEquipment;
    }

    /**
     * Sets the value of the divingEquipment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDivingEquipment(String value) {
        this.divingEquipment = value;
    }

    /**
     * Gets the value of the equipmentServicedInd property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public OLILUBOOLEAN getEquipmentServicedInd() {
        return equipmentServicedInd;
    }

    /**
     * Sets the value of the equipmentServicedInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public void setEquipmentServicedInd(OLILUBOOLEAN value) {
        this.equipmentServicedInd = value;
    }

    /**
     * Gets the value of the oLifEExtension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the oLifEExtension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOLifEExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OLifEExtensionType }
     * 
     * 
     */
    public List<OLifEExtensionType> getOLifEExtension() {
        if (oLifEExtension == null) {
            oLifEExtension = new ArrayList<OLifEExtensionType>();
        }
        return this.oLifEExtension;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the dataRep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataRep() {
        return dataRep;
    }

    /**
     * Sets the value of the dataRep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataRep(String value) {
        this.dataRep = value;
    }

}
