//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.13 at 07:49:02 PM IST 
//


package org.acord.standards.life._2;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for DiveDetail_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DiveDetail_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}DiveDetailKey" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}DiveDetailSysKey" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}NumberOfDivesLastYr" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}NumberOfDivesNextYr" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}MinDiveDepth" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}MaxDiveDepth" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}DiveDepthMeasureUnits" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}AvgDiveTimeLastYear" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}AvgDiveTimeNextYear" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}AvgDiveTimeMeasureUnits" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}OLifEExtension" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="DataRep" type="{http://ACORD.org/Standards/Life/2}DATAREP_TYPES" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DiveDetail_Type", propOrder = {
    "diveDetailKey",
    "diveDetailSysKey",
    "numberOfDivesLastYr",
    "numberOfDivesNextYr",
    "minDiveDepth",
    "maxDiveDepth",
    "diveDepthMeasureUnits",
    "avgDiveTimeLastYear",
    "avgDiveTimeNextYear",
    "avgDiveTimeMeasureUnits",
    "oLifEExtension"
})
public class DiveDetailType {

    @XmlElement(name = "DiveDetailKey")
    protected PERSISTKEY diveDetailKey;
    @XmlElement(name = "DiveDetailSysKey")
    protected List<SYSKEY> diveDetailSysKey;
    @XmlElement(name = "NumberOfDivesLastYr")
    protected BigInteger numberOfDivesLastYr;
    @XmlElement(name = "NumberOfDivesNextYr")
    protected BigInteger numberOfDivesNextYr;
    @XmlElement(name = "MinDiveDepth")
    protected Double minDiveDepth;
    @XmlElement(name = "MaxDiveDepth")
    protected Double maxDiveDepth;
    @XmlElement(name = "DiveDepthMeasureUnits")
    protected OLILUMEASUNITS diveDepthMeasureUnits;
    @XmlElement(name = "AvgDiveTimeLastYear")
    protected Double avgDiveTimeLastYear;
    @XmlElement(name = "AvgDiveTimeNextYear")
    protected Double avgDiveTimeNextYear;
    @XmlElement(name = "AvgDiveTimeMeasureUnits")
    protected OLILUMEASUNITS avgDiveTimeMeasureUnits;
    @XmlElement(name = "OLifEExtension")
    protected List<OLifEExtensionType> oLifEExtension;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "DataRep")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dataRep;

    /**
     * Gets the value of the diveDetailKey property.
     * 
     * @return
     *     possible object is
     *     {@link PERSISTKEY }
     *     
     */
    public PERSISTKEY getDiveDetailKey() {
        return diveDetailKey;
    }

    /**
     * Sets the value of the diveDetailKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link PERSISTKEY }
     *     
     */
    public void setDiveDetailKey(PERSISTKEY value) {
        this.diveDetailKey = value;
    }

    /**
     * Gets the value of the diveDetailSysKey property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the diveDetailSysKey property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDiveDetailSysKey().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SYSKEY }
     * 
     * 
     */
    public List<SYSKEY> getDiveDetailSysKey() {
        if (diveDetailSysKey == null) {
            diveDetailSysKey = new ArrayList<SYSKEY>();
        }
        return this.diveDetailSysKey;
    }

    /**
     * Gets the value of the numberOfDivesLastYr property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfDivesLastYr() {
        return numberOfDivesLastYr;
    }

    /**
     * Sets the value of the numberOfDivesLastYr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfDivesLastYr(BigInteger value) {
        this.numberOfDivesLastYr = value;
    }

    /**
     * Gets the value of the numberOfDivesNextYr property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfDivesNextYr() {
        return numberOfDivesNextYr;
    }

    /**
     * Sets the value of the numberOfDivesNextYr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfDivesNextYr(BigInteger value) {
        this.numberOfDivesNextYr = value;
    }

    /**
     * Gets the value of the minDiveDepth property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMinDiveDepth() {
        return minDiveDepth;
    }

    /**
     * Sets the value of the minDiveDepth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMinDiveDepth(Double value) {
        this.minDiveDepth = value;
    }

    /**
     * Gets the value of the maxDiveDepth property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMaxDiveDepth() {
        return maxDiveDepth;
    }

    /**
     * Sets the value of the maxDiveDepth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMaxDiveDepth(Double value) {
        this.maxDiveDepth = value;
    }

    /**
     * Gets the value of the diveDepthMeasureUnits property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUMEASUNITS }
     *     
     */
    public OLILUMEASUNITS getDiveDepthMeasureUnits() {
        return diveDepthMeasureUnits;
    }

    /**
     * Sets the value of the diveDepthMeasureUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUMEASUNITS }
     *     
     */
    public void setDiveDepthMeasureUnits(OLILUMEASUNITS value) {
        this.diveDepthMeasureUnits = value;
    }

    /**
     * Gets the value of the avgDiveTimeLastYear property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAvgDiveTimeLastYear() {
        return avgDiveTimeLastYear;
    }

    /**
     * Sets the value of the avgDiveTimeLastYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAvgDiveTimeLastYear(Double value) {
        this.avgDiveTimeLastYear = value;
    }

    /**
     * Gets the value of the avgDiveTimeNextYear property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAvgDiveTimeNextYear() {
        return avgDiveTimeNextYear;
    }

    /**
     * Sets the value of the avgDiveTimeNextYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAvgDiveTimeNextYear(Double value) {
        this.avgDiveTimeNextYear = value;
    }

    /**
     * Gets the value of the avgDiveTimeMeasureUnits property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUMEASUNITS }
     *     
     */
    public OLILUMEASUNITS getAvgDiveTimeMeasureUnits() {
        return avgDiveTimeMeasureUnits;
    }

    /**
     * Sets the value of the avgDiveTimeMeasureUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUMEASUNITS }
     *     
     */
    public void setAvgDiveTimeMeasureUnits(OLILUMEASUNITS value) {
        this.avgDiveTimeMeasureUnits = value;
    }

    /**
     * Gets the value of the oLifEExtension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the oLifEExtension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOLifEExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OLifEExtensionType }
     * 
     * 
     */
    public List<OLifEExtensionType> getOLifEExtension() {
        if (oLifEExtension == null) {
            oLifEExtension = new ArrayList<OLifEExtensionType>();
        }
        return this.oLifEExtension;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the dataRep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataRep() {
        return dataRep;
    }

    /**
     * Sets the value of the dataRep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataRep(String value) {
        this.dataRep = value;
    }

}
