//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.13 at 07:49:02 PM IST 
//


package org.acord.standards.life._2;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for ForeignTravelGuideline_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ForeignTravelGuideline_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}ForeignTravelGuidelineKey" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}ForeignTravelGuidelineSysKey" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}GuidelineFailInstructionType" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}TimingType" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}HistoryDuration" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}HistoryDurationQualifier" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}MaxActivityFrequency" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}ActivityFrequencyMode" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}GuidelineDescription" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}MaxTravelRiskRating" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}TravelPurposeInfo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}LocationRestrictionInfo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}TravelLocationRatingsInfo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}Attachment" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}OLifEExtension" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="DataRep" type="{http://ACORD.org/Standards/Life/2}DATAREP_TYPES" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ForeignTravelGuideline_Type", propOrder = {
    "foreignTravelGuidelineKey",
    "foreignTravelGuidelineSysKey",
    "guidelineFailInstructionType",
    "timingType",
    "historyDuration",
    "historyDurationQualifier",
    "maxActivityFrequency",
    "activityFrequencyMode",
    "guidelineDescription",
    "maxTravelRiskRating",
    "travelPurposeInfo",
    "locationRestrictionInfo",
    "travelLocationRatingsInfo",
    "attachment",
    "oLifEExtension"
})
public class ForeignTravelGuidelineType {

    @XmlElement(name = "ForeignTravelGuidelineKey")
    protected PERSISTKEY foreignTravelGuidelineKey;
    @XmlElement(name = "ForeignTravelGuidelineSysKey")
    protected List<SYSKEY> foreignTravelGuidelineSysKey;
    @XmlElement(name = "GuidelineFailInstructionType")
    protected OLILUGDLNFAILINST guidelineFailInstructionType;
    @XmlElement(name = "TimingType")
    protected OLILUTIMINGTYPE timingType;
    @XmlElement(name = "HistoryDuration")
    protected BigInteger historyDuration;
    @XmlElement(name = "HistoryDurationQualifier")
    protected OLILUMEASUNITS historyDurationQualifier;
    @XmlElement(name = "MaxActivityFrequency")
    protected BigInteger maxActivityFrequency;
    @XmlElement(name = "ActivityFrequencyMode")
    protected OLILUPARTFREQ activityFrequencyMode;
    @XmlElement(name = "GuidelineDescription")
    protected String guidelineDescription;
    @XmlElement(name = "MaxTravelRiskRating")
    protected OLILUTRAVELRISK maxTravelRiskRating;
    @XmlElement(name = "TravelPurposeInfo")
    protected List<TravelPurposeInfoType> travelPurposeInfo;
    @XmlElement(name = "LocationRestrictionInfo")
    protected List<LocationRestrictionInfoType> locationRestrictionInfo;
    @XmlElement(name = "TravelLocationRatingsInfo")
    protected List<TravelLocationRatingsInfoType> travelLocationRatingsInfo;
    @XmlElement(name = "Attachment")
    protected List<AttachmentType> attachment;
    @XmlElement(name = "OLifEExtension")
    protected List<OLifEExtensionType> oLifEExtension;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "DataRep")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dataRep;

    /**
     * Gets the value of the foreignTravelGuidelineKey property.
     * 
     * @return
     *     possible object is
     *     {@link PERSISTKEY }
     *     
     */
    public PERSISTKEY getForeignTravelGuidelineKey() {
        return foreignTravelGuidelineKey;
    }

    /**
     * Sets the value of the foreignTravelGuidelineKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link PERSISTKEY }
     *     
     */
    public void setForeignTravelGuidelineKey(PERSISTKEY value) {
        this.foreignTravelGuidelineKey = value;
    }

    /**
     * Gets the value of the foreignTravelGuidelineSysKey property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the foreignTravelGuidelineSysKey property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getForeignTravelGuidelineSysKey().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SYSKEY }
     * 
     * 
     */
    public List<SYSKEY> getForeignTravelGuidelineSysKey() {
        if (foreignTravelGuidelineSysKey == null) {
            foreignTravelGuidelineSysKey = new ArrayList<SYSKEY>();
        }
        return this.foreignTravelGuidelineSysKey;
    }

    /**
     * Gets the value of the guidelineFailInstructionType property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUGDLNFAILINST }
     *     
     */
    public OLILUGDLNFAILINST getGuidelineFailInstructionType() {
        return guidelineFailInstructionType;
    }

    /**
     * Sets the value of the guidelineFailInstructionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUGDLNFAILINST }
     *     
     */
    public void setGuidelineFailInstructionType(OLILUGDLNFAILINST value) {
        this.guidelineFailInstructionType = value;
    }

    /**
     * Gets the value of the timingType property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUTIMINGTYPE }
     *     
     */
    public OLILUTIMINGTYPE getTimingType() {
        return timingType;
    }

    /**
     * Sets the value of the timingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUTIMINGTYPE }
     *     
     */
    public void setTimingType(OLILUTIMINGTYPE value) {
        this.timingType = value;
    }

    /**
     * Gets the value of the historyDuration property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHistoryDuration() {
        return historyDuration;
    }

    /**
     * Sets the value of the historyDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHistoryDuration(BigInteger value) {
        this.historyDuration = value;
    }

    /**
     * Gets the value of the historyDurationQualifier property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUMEASUNITS }
     *     
     */
    public OLILUMEASUNITS getHistoryDurationQualifier() {
        return historyDurationQualifier;
    }

    /**
     * Sets the value of the historyDurationQualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUMEASUNITS }
     *     
     */
    public void setHistoryDurationQualifier(OLILUMEASUNITS value) {
        this.historyDurationQualifier = value;
    }

    /**
     * Gets the value of the maxActivityFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxActivityFrequency() {
        return maxActivityFrequency;
    }

    /**
     * Sets the value of the maxActivityFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxActivityFrequency(BigInteger value) {
        this.maxActivityFrequency = value;
    }

    /**
     * Gets the value of the activityFrequencyMode property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUPARTFREQ }
     *     
     */
    public OLILUPARTFREQ getActivityFrequencyMode() {
        return activityFrequencyMode;
    }

    /**
     * Sets the value of the activityFrequencyMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUPARTFREQ }
     *     
     */
    public void setActivityFrequencyMode(OLILUPARTFREQ value) {
        this.activityFrequencyMode = value;
    }

    /**
     * Gets the value of the guidelineDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuidelineDescription() {
        return guidelineDescription;
    }

    /**
     * Sets the value of the guidelineDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuidelineDescription(String value) {
        this.guidelineDescription = value;
    }

    /**
     * Gets the value of the maxTravelRiskRating property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUTRAVELRISK }
     *     
     */
    public OLILUTRAVELRISK getMaxTravelRiskRating() {
        return maxTravelRiskRating;
    }

    /**
     * Sets the value of the maxTravelRiskRating property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUTRAVELRISK }
     *     
     */
    public void setMaxTravelRiskRating(OLILUTRAVELRISK value) {
        this.maxTravelRiskRating = value;
    }

    /**
     * Gets the value of the travelPurposeInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the travelPurposeInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTravelPurposeInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TravelPurposeInfoType }
     * 
     * 
     */
    public List<TravelPurposeInfoType> getTravelPurposeInfo() {
        if (travelPurposeInfo == null) {
            travelPurposeInfo = new ArrayList<TravelPurposeInfoType>();
        }
        return this.travelPurposeInfo;
    }

    /**
     * Gets the value of the locationRestrictionInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the locationRestrictionInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocationRestrictionInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocationRestrictionInfoType }
     * 
     * 
     */
    public List<LocationRestrictionInfoType> getLocationRestrictionInfo() {
        if (locationRestrictionInfo == null) {
            locationRestrictionInfo = new ArrayList<LocationRestrictionInfoType>();
        }
        return this.locationRestrictionInfo;
    }

    /**
     * Gets the value of the travelLocationRatingsInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the travelLocationRatingsInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTravelLocationRatingsInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TravelLocationRatingsInfoType }
     * 
     * 
     */
    public List<TravelLocationRatingsInfoType> getTravelLocationRatingsInfo() {
        if (travelLocationRatingsInfo == null) {
            travelLocationRatingsInfo = new ArrayList<TravelLocationRatingsInfoType>();
        }
        return this.travelLocationRatingsInfo;
    }

    /**
     * Gets the value of the attachment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attachment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttachment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AttachmentType }
     * 
     * 
     */
    public List<AttachmentType> getAttachment() {
        if (attachment == null) {
            attachment = new ArrayList<AttachmentType>();
        }
        return this.attachment;
    }

    /**
     * Gets the value of the oLifEExtension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the oLifEExtension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOLifEExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OLifEExtensionType }
     * 
     * 
     */
    public List<OLifEExtensionType> getOLifEExtension() {
        if (oLifEExtension == null) {
            oLifEExtension = new ArrayList<OLifEExtensionType>();
        }
        return this.oLifEExtension;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the dataRep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataRep() {
        return dataRep;
    }

    /**
     * Sets the value of the dataRep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataRep(String value) {
        this.dataRep = value;
    }

}
