//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.13 at 07:49:02 PM IST 
//


package org.acord.standards.life._2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for FormInstanceRequest_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FormInstanceRequest_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}FormInstanceRequestKey" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}FormInstanceRequestSysKey" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}FormInstanceCategory" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}FormInstanceKey" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}FormName" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}FormInstanceVersion" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}RequestedLanguage" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}CreationDate" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}CreationTime" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}ReprintInd" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}FormInstanceDestination" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}IllustrationRequest" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}IllustrationResult" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}KeyedValue" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}OLifEExtension" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="DataRep" type="{http://ACORD.org/Standards/Life/2}DATAREP_TYPES" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FormInstanceRequest_Type", propOrder = {
    "formInstanceRequestKey",
    "formInstanceRequestSysKey",
    "formInstanceCategory",
    "formInstanceKey",
    "formName",
    "formInstanceVersion",
    "requestedLanguage",
    "creationDate",
    "creationTime",
    "reprintInd",
    "formInstanceDestination",
    "illustrationRequest",
    "illustrationResult",
    "keyedValue",
    "oLifEExtension"
})
public class FormInstanceRequestType {

    @XmlElement(name = "FormInstanceRequestKey")
    protected PERSISTKEY formInstanceRequestKey;
    @XmlElement(name = "FormInstanceRequestSysKey")
    protected List<SYSKEY> formInstanceRequestSysKey;
    @XmlElement(name = "FormInstanceCategory")
    protected String formInstanceCategory;
    @XmlElement(name = "FormInstanceKey")
    protected PERSISTKEY formInstanceKey;
    @XmlElement(name = "FormName")
    protected String formName;
    @XmlElement(name = "FormInstanceVersion")
    protected String formInstanceVersion;
    @XmlElement(name = "RequestedLanguage")
    protected OLILUCLIENTLANGUAGES requestedLanguage;
    @XmlElement(name = "CreationDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar creationDate;
    @XmlElement(name = "CreationTime")
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar creationTime;
    @XmlElement(name = "ReprintInd")
    protected OLILUBOOLEAN reprintInd;
    @XmlElement(name = "FormInstanceDestination")
    protected List<FormInstanceDestinationType> formInstanceDestination;
    @XmlElement(name = "IllustrationRequest")
    protected IllustrationRequestType illustrationRequest;
    @XmlElement(name = "IllustrationResult")
    protected IllustrationResultType illustrationResult;
    @XmlElement(name = "KeyedValue")
    protected List<KeyedValueType> keyedValue;
    @XmlElement(name = "OLifEExtension")
    protected List<OLifEExtensionType> oLifEExtension;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "DataRep")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dataRep;

    /**
     * Gets the value of the formInstanceRequestKey property.
     * 
     * @return
     *     possible object is
     *     {@link PERSISTKEY }
     *     
     */
    public PERSISTKEY getFormInstanceRequestKey() {
        return formInstanceRequestKey;
    }

    /**
     * Sets the value of the formInstanceRequestKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link PERSISTKEY }
     *     
     */
    public void setFormInstanceRequestKey(PERSISTKEY value) {
        this.formInstanceRequestKey = value;
    }

    /**
     * Gets the value of the formInstanceRequestSysKey property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the formInstanceRequestSysKey property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFormInstanceRequestSysKey().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SYSKEY }
     * 
     * 
     */
    public List<SYSKEY> getFormInstanceRequestSysKey() {
        if (formInstanceRequestSysKey == null) {
            formInstanceRequestSysKey = new ArrayList<SYSKEY>();
        }
        return this.formInstanceRequestSysKey;
    }

    /**
     * Gets the value of the formInstanceCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormInstanceCategory() {
        return formInstanceCategory;
    }

    /**
     * Sets the value of the formInstanceCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormInstanceCategory(String value) {
        this.formInstanceCategory = value;
    }

    /**
     * Gets the value of the formInstanceKey property.
     * 
     * @return
     *     possible object is
     *     {@link PERSISTKEY }
     *     
     */
    public PERSISTKEY getFormInstanceKey() {
        return formInstanceKey;
    }

    /**
     * Sets the value of the formInstanceKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link PERSISTKEY }
     *     
     */
    public void setFormInstanceKey(PERSISTKEY value) {
        this.formInstanceKey = value;
    }

    /**
     * Gets the value of the formName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormName() {
        return formName;
    }

    /**
     * Sets the value of the formName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormName(String value) {
        this.formName = value;
    }

    /**
     * Gets the value of the formInstanceVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormInstanceVersion() {
        return formInstanceVersion;
    }

    /**
     * Sets the value of the formInstanceVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormInstanceVersion(String value) {
        this.formInstanceVersion = value;
    }

    /**
     * Gets the value of the requestedLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUCLIENTLANGUAGES }
     *     
     */
    public OLILUCLIENTLANGUAGES getRequestedLanguage() {
        return requestedLanguage;
    }

    /**
     * Sets the value of the requestedLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUCLIENTLANGUAGES }
     *     
     */
    public void setRequestedLanguage(OLILUCLIENTLANGUAGES value) {
        this.requestedLanguage = value;
    }

    /**
     * Gets the value of the creationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationDate(XMLGregorianCalendar value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the creationTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationTime() {
        return creationTime;
    }

    /**
     * Sets the value of the creationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationTime(XMLGregorianCalendar value) {
        this.creationTime = value;
    }

    /**
     * Gets the value of the reprintInd property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public OLILUBOOLEAN getReprintInd() {
        return reprintInd;
    }

    /**
     * Sets the value of the reprintInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public void setReprintInd(OLILUBOOLEAN value) {
        this.reprintInd = value;
    }

    /**
     * Gets the value of the formInstanceDestination property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the formInstanceDestination property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFormInstanceDestination().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FormInstanceDestinationType }
     * 
     * 
     */
    public List<FormInstanceDestinationType> getFormInstanceDestination() {
        if (formInstanceDestination == null) {
            formInstanceDestination = new ArrayList<FormInstanceDestinationType>();
        }
        return this.formInstanceDestination;
    }

    /**
     * Gets the value of the illustrationRequest property.
     * 
     * @return
     *     possible object is
     *     {@link IllustrationRequestType }
     *     
     */
    public IllustrationRequestType getIllustrationRequest() {
        return illustrationRequest;
    }

    /**
     * Sets the value of the illustrationRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link IllustrationRequestType }
     *     
     */
    public void setIllustrationRequest(IllustrationRequestType value) {
        this.illustrationRequest = value;
    }

    /**
     * Gets the value of the illustrationResult property.
     * 
     * @return
     *     possible object is
     *     {@link IllustrationResultType }
     *     
     */
    public IllustrationResultType getIllustrationResult() {
        return illustrationResult;
    }

    /**
     * Sets the value of the illustrationResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link IllustrationResultType }
     *     
     */
    public void setIllustrationResult(IllustrationResultType value) {
        this.illustrationResult = value;
    }

    /**
     * Gets the value of the keyedValue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the keyedValue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKeyedValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KeyedValueType }
     * 
     * 
     */
    public List<KeyedValueType> getKeyedValue() {
        if (keyedValue == null) {
            keyedValue = new ArrayList<KeyedValueType>();
        }
        return this.keyedValue;
    }

    /**
     * Gets the value of the oLifEExtension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the oLifEExtension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOLifEExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OLifEExtensionType }
     * 
     * 
     */
    public List<OLifEExtensionType> getOLifEExtension() {
        if (oLifEExtension == null) {
            oLifEExtension = new ArrayList<OLifEExtensionType>();
        }
        return this.oLifEExtension;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the dataRep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataRep() {
        return dataRep;
    }

    /**
     * Sets the value of the dataRep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataRep(String value) {
        this.dataRep = value;
    }

}
