//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.13 at 07:49:02 PM IST 
//


package org.acord.standards.life._2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LevelizationOptionCC_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LevelizationOptionCC_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}LevelizationOption" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}PaymentModeMethProduct" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LevelizationOptionCC_Type", propOrder = {
    "levelizationOption",
    "paymentModeMethProduct"
})
public class LevelizationOptionCCType {

    @XmlElement(name = "LevelizationOption")
    protected List<OLILULEVELIZEDOPT> levelizationOption;
    @XmlElement(name = "PaymentModeMethProduct")
    protected List<PaymentModeMethProductType> paymentModeMethProduct;

    /**
     * Gets the value of the levelizationOption property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the levelizationOption property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLevelizationOption().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OLILULEVELIZEDOPT }
     * 
     * 
     */
    public List<OLILULEVELIZEDOPT> getLevelizationOption() {
        if (levelizationOption == null) {
            levelizationOption = new ArrayList<OLILULEVELIZEDOPT>();
        }
        return this.levelizationOption;
    }

    /**
     * Gets the value of the paymentModeMethProduct property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paymentModeMethProduct property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPaymentModeMethProduct().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PaymentModeMethProductType }
     * 
     * 
     */
    public List<PaymentModeMethProductType> getPaymentModeMethProduct() {
        if (paymentModeMethProduct == null) {
            paymentModeMethProduct = new ArrayList<PaymentModeMethProductType>();
        }
        return this.paymentModeMethProduct;
    }

}
