//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.13 at 07:49:02 PM IST 
//


package org.acord.standards.life._2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for License_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="License_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}LicenseKey" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}LicenseSysKey" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}LicenseID" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}LicenseNum" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}LicenseCountry" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}LicenseState" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}LicenseType" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}LicenseClassType" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}LicenseStatus" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}LicenseStatusDate" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}LicenseStatusReason" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}EffDate" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}ExpDate" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{http://ACORD.org/Standards/Life/2}OriginationDate" minOccurs="0"/>
 *           &lt;element ref="{http://ACORD.org/Standards/Life/2}OriginationPartialDate" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}NameOnLicense" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}ResidentOfState" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}GovtID" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}GovtIDTC" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}LicenseInterruptedInd" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}LicenseInterruptedReason" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}RenewalDate" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}LevelDesc" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}Exam" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}LineOfAuthority" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}RequirementInfo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}Fee" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}Attachment" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}OLifEExtension" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="RegistrationRefID" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="DataRep" type="{http://ACORD.org/Standards/Life/2}DATAREP_TYPES" />
 *       &lt;attribute name="LicenseAddressID" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="AgencyAffiliationID" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "License_Type", propOrder = {
    "licenseKey",
    "licenseSysKey",
    "licenseID",
    "licenseNum",
    "licenseCountry",
    "licenseState",
    "licenseType",
    "licenseClassType",
    "licenseStatus",
    "licenseStatusDate",
    "licenseStatusReason",
    "effDate",
    "expDate",
    "originationDate",
    "originationPartialDate",
    "nameOnLicense",
    "residentOfState",
    "govtID",
    "govtIDTC",
    "licenseInterruptedInd",
    "licenseInterruptedReason",
    "renewalDate",
    "levelDesc",
    "exam",
    "lineOfAuthority",
    "requirementInfo",
    "fee",
    "attachment",
    "oLifEExtension"
})
public class LicenseType {

    @XmlElement(name = "LicenseKey")
    protected PERSISTKEY licenseKey;
    @XmlElement(name = "LicenseSysKey")
    protected List<SYSKEY> licenseSysKey;
    @XmlElement(name = "LicenseID")
    protected String licenseID;
    @XmlElement(name = "LicenseNum")
    protected String licenseNum;
    @XmlElement(name = "LicenseCountry")
    protected OLILUNATION licenseCountry;
    @XmlElement(name = "LicenseState")
    protected OLILUSTATE licenseState;
    @XmlElement(name = "LicenseType")
    protected OLILULICENSETYPE licenseType;
    @XmlElement(name = "LicenseClassType")
    protected OLILULICENSECLASSTYPE licenseClassType;
    @XmlElement(name = "LicenseStatus")
    protected OLILULICENSESTATUS licenseStatus;
    @XmlElement(name = "LicenseStatusDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar licenseStatusDate;
    @XmlElement(name = "LicenseStatusReason")
    protected String licenseStatusReason;
    @XmlElement(name = "EffDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar effDate;
    @XmlElement(name = "ExpDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar expDate;
    @XmlElement(name = "OriginationDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar originationDate;
    @XmlElement(name = "OriginationPartialDate")
    protected String originationPartialDate;
    @XmlElement(name = "NameOnLicense")
    protected String nameOnLicense;
    @XmlElement(name = "ResidentOfState")
    protected OLILUBOOLEAN residentOfState;
    @XmlElement(name = "GovtID")
    protected String govtID;
    @XmlElement(name = "GovtIDTC")
    protected OLILUGOVTIDTC govtIDTC;
    @XmlElement(name = "LicenseInterruptedInd")
    protected OLILUBOOLEAN licenseInterruptedInd;
    @XmlElement(name = "LicenseInterruptedReason")
    protected String licenseInterruptedReason;
    @XmlElement(name = "RenewalDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar renewalDate;
    @XmlElement(name = "LevelDesc")
    protected String levelDesc;
    @XmlElement(name = "Exam")
    protected List<ExamType> exam;
    @XmlElement(name = "LineOfAuthority")
    protected List<LineOfAuthorityType> lineOfAuthority;
    @XmlElement(name = "RequirementInfo")
    protected List<RequirementInfoType> requirementInfo;
    @XmlElement(name = "Fee")
    protected List<FeeType> fee;
    @XmlElement(name = "Attachment")
    protected List<AttachmentType> attachment;
    @XmlElement(name = "OLifEExtension")
    protected List<OLifEExtensionType> oLifEExtension;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "RegistrationRefID")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object registrationRefID;
    @XmlAttribute(name = "DataRep")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dataRep;
    @XmlAttribute(name = "LicenseAddressID")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object licenseAddressID;
    @XmlAttribute(name = "AgencyAffiliationID")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object agencyAffiliationID;

    /**
     * Gets the value of the licenseKey property.
     * 
     * @return
     *     possible object is
     *     {@link PERSISTKEY }
     *     
     */
    public PERSISTKEY getLicenseKey() {
        return licenseKey;
    }

    /**
     * Sets the value of the licenseKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link PERSISTKEY }
     *     
     */
    public void setLicenseKey(PERSISTKEY value) {
        this.licenseKey = value;
    }

    /**
     * Gets the value of the licenseSysKey property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the licenseSysKey property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLicenseSysKey().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SYSKEY }
     * 
     * 
     */
    public List<SYSKEY> getLicenseSysKey() {
        if (licenseSysKey == null) {
            licenseSysKey = new ArrayList<SYSKEY>();
        }
        return this.licenseSysKey;
    }

    /**
     * Gets the value of the licenseID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicenseID() {
        return licenseID;
    }

    /**
     * Sets the value of the licenseID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicenseID(String value) {
        this.licenseID = value;
    }

    /**
     * Gets the value of the licenseNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicenseNum() {
        return licenseNum;
    }

    /**
     * Sets the value of the licenseNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicenseNum(String value) {
        this.licenseNum = value;
    }

    /**
     * Gets the value of the licenseCountry property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUNATION }
     *     
     */
    public OLILUNATION getLicenseCountry() {
        return licenseCountry;
    }

    /**
     * Sets the value of the licenseCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUNATION }
     *     
     */
    public void setLicenseCountry(OLILUNATION value) {
        this.licenseCountry = value;
    }

    /**
     * Gets the value of the licenseState property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUSTATE }
     *     
     */
    public OLILUSTATE getLicenseState() {
        return licenseState;
    }

    /**
     * Sets the value of the licenseState property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUSTATE }
     *     
     */
    public void setLicenseState(OLILUSTATE value) {
        this.licenseState = value;
    }

    /**
     * Gets the value of the licenseType property.
     * 
     * @return
     *     possible object is
     *     {@link OLILULICENSETYPE }
     *     
     */
    public OLILULICENSETYPE getLicenseType() {
        return licenseType;
    }

    /**
     * Sets the value of the licenseType property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILULICENSETYPE }
     *     
     */
    public void setLicenseType(OLILULICENSETYPE value) {
        this.licenseType = value;
    }

    /**
     * Gets the value of the licenseClassType property.
     * 
     * @return
     *     possible object is
     *     {@link OLILULICENSECLASSTYPE }
     *     
     */
    public OLILULICENSECLASSTYPE getLicenseClassType() {
        return licenseClassType;
    }

    /**
     * Sets the value of the licenseClassType property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILULICENSECLASSTYPE }
     *     
     */
    public void setLicenseClassType(OLILULICENSECLASSTYPE value) {
        this.licenseClassType = value;
    }

    /**
     * Gets the value of the licenseStatus property.
     * 
     * @return
     *     possible object is
     *     {@link OLILULICENSESTATUS }
     *     
     */
    public OLILULICENSESTATUS getLicenseStatus() {
        return licenseStatus;
    }

    /**
     * Sets the value of the licenseStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILULICENSESTATUS }
     *     
     */
    public void setLicenseStatus(OLILULICENSESTATUS value) {
        this.licenseStatus = value;
    }

    /**
     * Gets the value of the licenseStatusDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLicenseStatusDate() {
        return licenseStatusDate;
    }

    /**
     * Sets the value of the licenseStatusDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLicenseStatusDate(XMLGregorianCalendar value) {
        this.licenseStatusDate = value;
    }

    /**
     * Gets the value of the licenseStatusReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicenseStatusReason() {
        return licenseStatusReason;
    }

    /**
     * Sets the value of the licenseStatusReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicenseStatusReason(String value) {
        this.licenseStatusReason = value;
    }

    /**
     * Gets the value of the effDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEffDate() {
        return effDate;
    }

    /**
     * Sets the value of the effDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEffDate(XMLGregorianCalendar value) {
        this.effDate = value;
    }

    /**
     * Gets the value of the expDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpDate() {
        return expDate;
    }

    /**
     * Sets the value of the expDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpDate(XMLGregorianCalendar value) {
        this.expDate = value;
    }

    /**
     * Gets the value of the originationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOriginationDate() {
        return originationDate;
    }

    /**
     * Sets the value of the originationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOriginationDate(XMLGregorianCalendar value) {
        this.originationDate = value;
    }

    /**
     * Gets the value of the originationPartialDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginationPartialDate() {
        return originationPartialDate;
    }

    /**
     * Sets the value of the originationPartialDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginationPartialDate(String value) {
        this.originationPartialDate = value;
    }

    /**
     * Gets the value of the nameOnLicense property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameOnLicense() {
        return nameOnLicense;
    }

    /**
     * Sets the value of the nameOnLicense property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameOnLicense(String value) {
        this.nameOnLicense = value;
    }

    /**
     * Gets the value of the residentOfState property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public OLILUBOOLEAN getResidentOfState() {
        return residentOfState;
    }

    /**
     * Sets the value of the residentOfState property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public void setResidentOfState(OLILUBOOLEAN value) {
        this.residentOfState = value;
    }

    /**
     * Gets the value of the govtID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGovtID() {
        return govtID;
    }

    /**
     * Sets the value of the govtID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGovtID(String value) {
        this.govtID = value;
    }

    /**
     * Gets the value of the govtIDTC property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUGOVTIDTC }
     *     
     */
    public OLILUGOVTIDTC getGovtIDTC() {
        return govtIDTC;
    }

    /**
     * Sets the value of the govtIDTC property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUGOVTIDTC }
     *     
     */
    public void setGovtIDTC(OLILUGOVTIDTC value) {
        this.govtIDTC = value;
    }

    /**
     * Gets the value of the licenseInterruptedInd property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public OLILUBOOLEAN getLicenseInterruptedInd() {
        return licenseInterruptedInd;
    }

    /**
     * Sets the value of the licenseInterruptedInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public void setLicenseInterruptedInd(OLILUBOOLEAN value) {
        this.licenseInterruptedInd = value;
    }

    /**
     * Gets the value of the licenseInterruptedReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicenseInterruptedReason() {
        return licenseInterruptedReason;
    }

    /**
     * Sets the value of the licenseInterruptedReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicenseInterruptedReason(String value) {
        this.licenseInterruptedReason = value;
    }

    /**
     * Gets the value of the renewalDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRenewalDate() {
        return renewalDate;
    }

    /**
     * Sets the value of the renewalDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRenewalDate(XMLGregorianCalendar value) {
        this.renewalDate = value;
    }

    /**
     * Gets the value of the levelDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLevelDesc() {
        return levelDesc;
    }

    /**
     * Sets the value of the levelDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLevelDesc(String value) {
        this.levelDesc = value;
    }

    /**
     * Gets the value of the exam property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the exam property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExam().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExamType }
     * 
     * 
     */
    public List<ExamType> getExam() {
        if (exam == null) {
            exam = new ArrayList<ExamType>();
        }
        return this.exam;
    }

    /**
     * Gets the value of the lineOfAuthority property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lineOfAuthority property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLineOfAuthority().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LineOfAuthorityType }
     * 
     * 
     */
    public List<LineOfAuthorityType> getLineOfAuthority() {
        if (lineOfAuthority == null) {
            lineOfAuthority = new ArrayList<LineOfAuthorityType>();
        }
        return this.lineOfAuthority;
    }

    /**
     * Gets the value of the requirementInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the requirementInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequirementInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RequirementInfoType }
     * 
     * 
     */
    public List<RequirementInfoType> getRequirementInfo() {
        if (requirementInfo == null) {
            requirementInfo = new ArrayList<RequirementInfoType>();
        }
        return this.requirementInfo;
    }

    /**
     * Gets the value of the fee property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fee property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFee().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FeeType }
     * 
     * 
     */
    public List<FeeType> getFee() {
        if (fee == null) {
            fee = new ArrayList<FeeType>();
        }
        return this.fee;
    }

    /**
     * Gets the value of the attachment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attachment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttachment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AttachmentType }
     * 
     * 
     */
    public List<AttachmentType> getAttachment() {
        if (attachment == null) {
            attachment = new ArrayList<AttachmentType>();
        }
        return this.attachment;
    }

    /**
     * Gets the value of the oLifEExtension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the oLifEExtension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOLifEExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OLifEExtensionType }
     * 
     * 
     */
    public List<OLifEExtensionType> getOLifEExtension() {
        if (oLifEExtension == null) {
            oLifEExtension = new ArrayList<OLifEExtensionType>();
        }
        return this.oLifEExtension;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the registrationRefID property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getRegistrationRefID() {
        return registrationRefID;
    }

    /**
     * Sets the value of the registrationRefID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setRegistrationRefID(Object value) {
        this.registrationRefID = value;
    }

    /**
     * Gets the value of the dataRep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataRep() {
        return dataRep;
    }

    /**
     * Sets the value of the dataRep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataRep(String value) {
        this.dataRep = value;
    }

    /**
     * Gets the value of the licenseAddressID property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getLicenseAddressID() {
        return licenseAddressID;
    }

    /**
     * Sets the value of the licenseAddressID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setLicenseAddressID(Object value) {
        this.licenseAddressID = value;
    }

    /**
     * Gets the value of the agencyAffiliationID property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAgencyAffiliationID() {
        return agencyAffiliationID;
    }

    /**
     * Sets the value of the agencyAffiliationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAgencyAffiliationID(Object value) {
        this.agencyAffiliationID = value;
    }

}
