//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.13 at 07:49:02 PM IST 
//


package org.acord.standards.life._2;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Payment_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Payment_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}PaymentKey" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}PaymentSysKey" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}PaymentForm" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}CreateCheckInd" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}PayeeRelationRoleCode" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}PayeeName" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}CheckNo" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}CheckDescription" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}VendorCode" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}PaymentAmt" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}SourceOfFundsTC" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}SourceOfFundsDetails" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}PaymentPartialInd" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}PaymentMethod" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}RetainedCommissionAmt" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}MoneyTransferType" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}CheckDate" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}CheckStubDetails" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}PaymentStatus" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}PaymentStatusDate" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}DateReceivedAtBank" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}DateDepositedByBank" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}ForeignPaymentInd" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}PaymentDraftDay" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}PaymentStatusReason" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}ReferenceNo" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}PaymentMailDate" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}ACHEntryClassType" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}PaymentDeliveryMethInfo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}Attachment" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}KeyedValue" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}OLifEExtension" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="PayeeID" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="BankHoldingID" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="HoldingID" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="DataRep" type="{http://ACORD.org/Standards/Life/2}DATAREP_TYPES" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Payment_Type", propOrder = {
    "paymentKey",
    "paymentSysKey",
    "paymentForm",
    "createCheckInd",
    "payeeRelationRoleCode",
    "payeeName",
    "checkNo",
    "checkDescription",
    "vendorCode",
    "paymentAmt",
    "sourceOfFundsTC",
    "sourceOfFundsDetails",
    "paymentPartialInd",
    "paymentMethod",
    "retainedCommissionAmt",
    "moneyTransferType",
    "checkDate",
    "checkStubDetails",
    "paymentStatus",
    "paymentStatusDate",
    "dateReceivedAtBank",
    "dateDepositedByBank",
    "foreignPaymentInd",
    "paymentDraftDay",
    "paymentStatusReason",
    "referenceNo",
    "paymentMailDate",
    "achEntryClassType",
    "paymentDeliveryMethInfo",
    "attachment",
    "keyedValue",
    "oLifEExtension"
})
public class PaymentType {

    @XmlElement(name = "PaymentKey")
    protected PERSISTKEY paymentKey;
    @XmlElement(name = "PaymentSysKey")
    protected List<SYSKEY> paymentSysKey;
    @XmlElement(name = "PaymentForm")
    protected OLILUPAYMENTFORM paymentForm;
    @XmlElement(name = "CreateCheckInd")
    protected OLILUBOOLEAN createCheckInd;
    @XmlElement(name = "PayeeRelationRoleCode")
    protected OLILUPARTICROLE payeeRelationRoleCode;
    @XmlElement(name = "PayeeName")
    protected String payeeName;
    @XmlElement(name = "CheckNo")
    protected String checkNo;
    @XmlElement(name = "CheckDescription")
    protected String checkDescription;
    @XmlElement(name = "VendorCode")
    protected String vendorCode;
    @XmlElement(name = "PaymentAmt")
    protected BigDecimal paymentAmt;
    @XmlElement(name = "SourceOfFundsTC")
    protected OLILUSOURCEOFFUNDS sourceOfFundsTC;
    @XmlElement(name = "SourceOfFundsDetails")
    protected String sourceOfFundsDetails;
    @XmlElement(name = "PaymentPartialInd")
    protected OLILUBOOLEAN paymentPartialInd;
    @XmlElement(name = "PaymentMethod")
    protected OLILUPAYMETHOD paymentMethod;
    @XmlElement(name = "RetainedCommissionAmt")
    protected BigDecimal retainedCommissionAmt;
    @XmlElement(name = "MoneyTransferType")
    protected OLILUMONEYTRSFR moneyTransferType;
    @XmlElement(name = "CheckDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar checkDate;
    @XmlElement(name = "CheckStubDetails")
    protected String checkStubDetails;
    @XmlElement(name = "PaymentStatus")
    protected OLILUPAYMENTSTATUS paymentStatus;
    @XmlElement(name = "PaymentStatusDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar paymentStatusDate;
    @XmlElement(name = "DateReceivedAtBank")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateReceivedAtBank;
    @XmlElement(name = "DateDepositedByBank")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateDepositedByBank;
    @XmlElement(name = "ForeignPaymentInd")
    protected OLILUBOOLEAN foreignPaymentInd;
    @XmlElement(name = "PaymentDraftDay")
    protected BigInteger paymentDraftDay;
    @XmlElement(name = "PaymentStatusReason")
    protected String paymentStatusReason;
    @XmlElement(name = "ReferenceNo")
    protected String referenceNo;
    @XmlElement(name = "PaymentMailDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar paymentMailDate;
    @XmlElement(name = "ACHEntryClassType")
    protected OLILUACHENTRYTYPE achEntryClassType;
    @XmlElement(name = "PaymentDeliveryMethInfo")
    protected List<PaymentDeliveryMethInfoType> paymentDeliveryMethInfo;
    @XmlElement(name = "Attachment")
    protected List<AttachmentType> attachment;
    @XmlElement(name = "KeyedValue")
    protected List<KeyedValueType> keyedValue;
    @XmlElement(name = "OLifEExtension")
    protected List<OLifEExtensionType> oLifEExtension;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "PayeeID")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object payeeID;
    @XmlAttribute(name = "BankHoldingID")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object bankHoldingID;
    @XmlAttribute(name = "HoldingID")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object holdingID;
    @XmlAttribute(name = "DataRep")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dataRep;

    /**
     * Gets the value of the paymentKey property.
     * 
     * @return
     *     possible object is
     *     {@link PERSISTKEY }
     *     
     */
    public PERSISTKEY getPaymentKey() {
        return paymentKey;
    }

    /**
     * Sets the value of the paymentKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link PERSISTKEY }
     *     
     */
    public void setPaymentKey(PERSISTKEY value) {
        this.paymentKey = value;
    }

    /**
     * Gets the value of the paymentSysKey property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paymentSysKey property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPaymentSysKey().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SYSKEY }
     * 
     * 
     */
    public List<SYSKEY> getPaymentSysKey() {
        if (paymentSysKey == null) {
            paymentSysKey = new ArrayList<SYSKEY>();
        }
        return this.paymentSysKey;
    }

    /**
     * Gets the value of the paymentForm property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUPAYMENTFORM }
     *     
     */
    public OLILUPAYMENTFORM getPaymentForm() {
        return paymentForm;
    }

    /**
     * Sets the value of the paymentForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUPAYMENTFORM }
     *     
     */
    public void setPaymentForm(OLILUPAYMENTFORM value) {
        this.paymentForm = value;
    }

    /**
     * Gets the value of the createCheckInd property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public OLILUBOOLEAN getCreateCheckInd() {
        return createCheckInd;
    }

    /**
     * Sets the value of the createCheckInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public void setCreateCheckInd(OLILUBOOLEAN value) {
        this.createCheckInd = value;
    }

    /**
     * Gets the value of the payeeRelationRoleCode property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUPARTICROLE }
     *     
     */
    public OLILUPARTICROLE getPayeeRelationRoleCode() {
        return payeeRelationRoleCode;
    }

    /**
     * Sets the value of the payeeRelationRoleCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUPARTICROLE }
     *     
     */
    public void setPayeeRelationRoleCode(OLILUPARTICROLE value) {
        this.payeeRelationRoleCode = value;
    }

    /**
     * Gets the value of the payeeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayeeName() {
        return payeeName;
    }

    /**
     * Sets the value of the payeeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayeeName(String value) {
        this.payeeName = value;
    }

    /**
     * Gets the value of the checkNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCheckNo() {
        return checkNo;
    }

    /**
     * Sets the value of the checkNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCheckNo(String value) {
        this.checkNo = value;
    }

    /**
     * Gets the value of the checkDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCheckDescription() {
        return checkDescription;
    }

    /**
     * Sets the value of the checkDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCheckDescription(String value) {
        this.checkDescription = value;
    }

    /**
     * Gets the value of the vendorCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorCode() {
        return vendorCode;
    }

    /**
     * Sets the value of the vendorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorCode(String value) {
        this.vendorCode = value;
    }

    /**
     * Gets the value of the paymentAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPaymentAmt() {
        return paymentAmt;
    }

    /**
     * Sets the value of the paymentAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPaymentAmt(BigDecimal value) {
        this.paymentAmt = value;
    }

    /**
     * Gets the value of the sourceOfFundsTC property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUSOURCEOFFUNDS }
     *     
     */
    public OLILUSOURCEOFFUNDS getSourceOfFundsTC() {
        return sourceOfFundsTC;
    }

    /**
     * Sets the value of the sourceOfFundsTC property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUSOURCEOFFUNDS }
     *     
     */
    public void setSourceOfFundsTC(OLILUSOURCEOFFUNDS value) {
        this.sourceOfFundsTC = value;
    }

    /**
     * Gets the value of the sourceOfFundsDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceOfFundsDetails() {
        return sourceOfFundsDetails;
    }

    /**
     * Sets the value of the sourceOfFundsDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceOfFundsDetails(String value) {
        this.sourceOfFundsDetails = value;
    }

    /**
     * Gets the value of the paymentPartialInd property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public OLILUBOOLEAN getPaymentPartialInd() {
        return paymentPartialInd;
    }

    /**
     * Sets the value of the paymentPartialInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public void setPaymentPartialInd(OLILUBOOLEAN value) {
        this.paymentPartialInd = value;
    }

    /**
     * Gets the value of the paymentMethod property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUPAYMETHOD }
     *     
     */
    public OLILUPAYMETHOD getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * Sets the value of the paymentMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUPAYMETHOD }
     *     
     */
    public void setPaymentMethod(OLILUPAYMETHOD value) {
        this.paymentMethod = value;
    }

    /**
     * Gets the value of the retainedCommissionAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRetainedCommissionAmt() {
        return retainedCommissionAmt;
    }

    /**
     * Sets the value of the retainedCommissionAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRetainedCommissionAmt(BigDecimal value) {
        this.retainedCommissionAmt = value;
    }

    /**
     * Gets the value of the moneyTransferType property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUMONEYTRSFR }
     *     
     */
    public OLILUMONEYTRSFR getMoneyTransferType() {
        return moneyTransferType;
    }

    /**
     * Sets the value of the moneyTransferType property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUMONEYTRSFR }
     *     
     */
    public void setMoneyTransferType(OLILUMONEYTRSFR value) {
        this.moneyTransferType = value;
    }

    /**
     * Gets the value of the checkDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCheckDate() {
        return checkDate;
    }

    /**
     * Sets the value of the checkDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCheckDate(XMLGregorianCalendar value) {
        this.checkDate = value;
    }

    /**
     * Gets the value of the checkStubDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCheckStubDetails() {
        return checkStubDetails;
    }

    /**
     * Sets the value of the checkStubDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCheckStubDetails(String value) {
        this.checkStubDetails = value;
    }

    /**
     * Gets the value of the paymentStatus property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUPAYMENTSTATUS }
     *     
     */
    public OLILUPAYMENTSTATUS getPaymentStatus() {
        return paymentStatus;
    }

    /**
     * Sets the value of the paymentStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUPAYMENTSTATUS }
     *     
     */
    public void setPaymentStatus(OLILUPAYMENTSTATUS value) {
        this.paymentStatus = value;
    }

    /**
     * Gets the value of the paymentStatusDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPaymentStatusDate() {
        return paymentStatusDate;
    }

    /**
     * Sets the value of the paymentStatusDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPaymentStatusDate(XMLGregorianCalendar value) {
        this.paymentStatusDate = value;
    }

    /**
     * Gets the value of the dateReceivedAtBank property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateReceivedAtBank() {
        return dateReceivedAtBank;
    }

    /**
     * Sets the value of the dateReceivedAtBank property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateReceivedAtBank(XMLGregorianCalendar value) {
        this.dateReceivedAtBank = value;
    }

    /**
     * Gets the value of the dateDepositedByBank property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateDepositedByBank() {
        return dateDepositedByBank;
    }

    /**
     * Sets the value of the dateDepositedByBank property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateDepositedByBank(XMLGregorianCalendar value) {
        this.dateDepositedByBank = value;
    }

    /**
     * Gets the value of the foreignPaymentInd property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public OLILUBOOLEAN getForeignPaymentInd() {
        return foreignPaymentInd;
    }

    /**
     * Sets the value of the foreignPaymentInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUBOOLEAN }
     *     
     */
    public void setForeignPaymentInd(OLILUBOOLEAN value) {
        this.foreignPaymentInd = value;
    }

    /**
     * Gets the value of the paymentDraftDay property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPaymentDraftDay() {
        return paymentDraftDay;
    }

    /**
     * Sets the value of the paymentDraftDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPaymentDraftDay(BigInteger value) {
        this.paymentDraftDay = value;
    }

    /**
     * Gets the value of the paymentStatusReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentStatusReason() {
        return paymentStatusReason;
    }

    /**
     * Sets the value of the paymentStatusReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentStatusReason(String value) {
        this.paymentStatusReason = value;
    }

    /**
     * Gets the value of the referenceNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceNo() {
        return referenceNo;
    }

    /**
     * Sets the value of the referenceNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceNo(String value) {
        this.referenceNo = value;
    }

    /**
     * Gets the value of the paymentMailDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPaymentMailDate() {
        return paymentMailDate;
    }

    /**
     * Sets the value of the paymentMailDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPaymentMailDate(XMLGregorianCalendar value) {
        this.paymentMailDate = value;
    }

    /**
     * Gets the value of the achEntryClassType property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUACHENTRYTYPE }
     *     
     */
    public OLILUACHENTRYTYPE getACHEntryClassType() {
        return achEntryClassType;
    }

    /**
     * Sets the value of the achEntryClassType property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUACHENTRYTYPE }
     *     
     */
    public void setACHEntryClassType(OLILUACHENTRYTYPE value) {
        this.achEntryClassType = value;
    }

    /**
     * Gets the value of the paymentDeliveryMethInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paymentDeliveryMethInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPaymentDeliveryMethInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PaymentDeliveryMethInfoType }
     * 
     * 
     */
    public List<PaymentDeliveryMethInfoType> getPaymentDeliveryMethInfo() {
        if (paymentDeliveryMethInfo == null) {
            paymentDeliveryMethInfo = new ArrayList<PaymentDeliveryMethInfoType>();
        }
        return this.paymentDeliveryMethInfo;
    }

    /**
     * Gets the value of the attachment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attachment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttachment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AttachmentType }
     * 
     * 
     */
    public List<AttachmentType> getAttachment() {
        if (attachment == null) {
            attachment = new ArrayList<AttachmentType>();
        }
        return this.attachment;
    }

    /**
     * Gets the value of the keyedValue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the keyedValue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKeyedValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KeyedValueType }
     * 
     * 
     */
    public List<KeyedValueType> getKeyedValue() {
        if (keyedValue == null) {
            keyedValue = new ArrayList<KeyedValueType>();
        }
        return this.keyedValue;
    }

    /**
     * Gets the value of the oLifEExtension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the oLifEExtension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOLifEExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OLifEExtensionType }
     * 
     * 
     */
    public List<OLifEExtensionType> getOLifEExtension() {
        if (oLifEExtension == null) {
            oLifEExtension = new ArrayList<OLifEExtensionType>();
        }
        return this.oLifEExtension;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the payeeID property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPayeeID() {
        return payeeID;
    }

    /**
     * Sets the value of the payeeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPayeeID(Object value) {
        this.payeeID = value;
    }

    /**
     * Gets the value of the bankHoldingID property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getBankHoldingID() {
        return bankHoldingID;
    }

    /**
     * Sets the value of the bankHoldingID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setBankHoldingID(Object value) {
        this.bankHoldingID = value;
    }

    /**
     * Gets the value of the holdingID property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getHoldingID() {
        return holdingID;
    }

    /**
     * Sets the value of the holdingID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setHoldingID(Object value) {
        this.holdingID = value;
    }

    /**
     * Gets the value of the dataRep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataRep() {
        return dataRep;
    }

    /**
     * Sets the value of the dataRep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataRep(String value) {
        this.dataRep = value;
    }

}
