//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.13 at 07:49:02 PM IST 
//


package org.acord.standards.life._2;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PeriodCertainCC_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PeriodCertainCC_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}PeriodCertainMode"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}PeriodCertainPeriods"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}IncomeStartDateMaxMonths" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}MinIssueAge" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}MaxIssueAge" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}MinIssueAgeOwner" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}MaxIssueAgeOwner" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}FeatureOptConflict" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}QualifiedPlanCC" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}QualifiedPlanOption" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PeriodCertainCC_Type", propOrder = {
    "periodCertainMode",
    "periodCertainPeriods",
    "incomeStartDateMaxMonths",
    "minIssueAge",
    "maxIssueAge",
    "minIssueAgeOwner",
    "maxIssueAgeOwner",
    "featureOptConflict",
    "qualifiedPlanCC",
    "qualifiedPlanOption"
})
public class PeriodCertainCCType {

    @XmlElement(name = "PeriodCertainMode", required = true)
    protected OLILUPAYMODE periodCertainMode;
    @XmlElement(name = "PeriodCertainPeriods", required = true)
    protected BigInteger periodCertainPeriods;
    @XmlElement(name = "IncomeStartDateMaxMonths")
    protected BigInteger incomeStartDateMaxMonths;
    @XmlElement(name = "MinIssueAge")
    protected BigInteger minIssueAge;
    @XmlElement(name = "MaxIssueAge")
    protected BigInteger maxIssueAge;
    @XmlElement(name = "MinIssueAgeOwner")
    protected BigInteger minIssueAgeOwner;
    @XmlElement(name = "MaxIssueAgeOwner")
    protected BigInteger maxIssueAgeOwner;
    @XmlElement(name = "FeatureOptConflict")
    protected List<FeatureOptConflictType> featureOptConflict;
    @XmlElement(name = "QualifiedPlanCC")
    protected QualifiedPlanCCType qualifiedPlanCC;
    @XmlElement(name = "QualifiedPlanOption")
    protected List<QualifiedPlanOptionType> qualifiedPlanOption;

    /**
     * Gets the value of the periodCertainMode property.
     * 
     * @return
     *     possible object is
     *     {@link OLILUPAYMODE }
     *     
     */
    public OLILUPAYMODE getPeriodCertainMode() {
        return periodCertainMode;
    }

    /**
     * Sets the value of the periodCertainMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLILUPAYMODE }
     *     
     */
    public void setPeriodCertainMode(OLILUPAYMODE value) {
        this.periodCertainMode = value;
    }

    /**
     * Gets the value of the periodCertainPeriods property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPeriodCertainPeriods() {
        return periodCertainPeriods;
    }

    /**
     * Sets the value of the periodCertainPeriods property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPeriodCertainPeriods(BigInteger value) {
        this.periodCertainPeriods = value;
    }

    /**
     * Gets the value of the incomeStartDateMaxMonths property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIncomeStartDateMaxMonths() {
        return incomeStartDateMaxMonths;
    }

    /**
     * Sets the value of the incomeStartDateMaxMonths property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIncomeStartDateMaxMonths(BigInteger value) {
        this.incomeStartDateMaxMonths = value;
    }

    /**
     * Gets the value of the minIssueAge property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMinIssueAge() {
        return minIssueAge;
    }

    /**
     * Sets the value of the minIssueAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMinIssueAge(BigInteger value) {
        this.minIssueAge = value;
    }

    /**
     * Gets the value of the maxIssueAge property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxIssueAge() {
        return maxIssueAge;
    }

    /**
     * Sets the value of the maxIssueAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxIssueAge(BigInteger value) {
        this.maxIssueAge = value;
    }

    /**
     * Gets the value of the minIssueAgeOwner property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMinIssueAgeOwner() {
        return minIssueAgeOwner;
    }

    /**
     * Sets the value of the minIssueAgeOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMinIssueAgeOwner(BigInteger value) {
        this.minIssueAgeOwner = value;
    }

    /**
     * Gets the value of the maxIssueAgeOwner property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxIssueAgeOwner() {
        return maxIssueAgeOwner;
    }

    /**
     * Sets the value of the maxIssueAgeOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxIssueAgeOwner(BigInteger value) {
        this.maxIssueAgeOwner = value;
    }

    /**
     * Gets the value of the featureOptConflict property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the featureOptConflict property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFeatureOptConflict().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FeatureOptConflictType }
     * 
     * 
     */
    public List<FeatureOptConflictType> getFeatureOptConflict() {
        if (featureOptConflict == null) {
            featureOptConflict = new ArrayList<FeatureOptConflictType>();
        }
        return this.featureOptConflict;
    }

    /**
     * Gets the value of the qualifiedPlanCC property.
     * 
     * @return
     *     possible object is
     *     {@link QualifiedPlanCCType }
     *     
     */
    public QualifiedPlanCCType getQualifiedPlanCC() {
        return qualifiedPlanCC;
    }

    /**
     * Sets the value of the qualifiedPlanCC property.
     * 
     * @param value
     *     allowed object is
     *     {@link QualifiedPlanCCType }
     *     
     */
    public void setQualifiedPlanCC(QualifiedPlanCCType value) {
        this.qualifiedPlanCC = value;
    }

    /**
     * Gets the value of the qualifiedPlanOption property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qualifiedPlanOption property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQualifiedPlanOption().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QualifiedPlanOptionType }
     * 
     * 
     */
    public List<QualifiedPlanOptionType> getQualifiedPlanOption() {
        if (qualifiedPlanOption == null) {
            qualifiedPlanOption = new ArrayList<QualifiedPlanOptionType>();
        }
        return this.qualifiedPlanOption;
    }

}
