//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.13 at 07:49:02 PM IST 
//


package org.acord.standards.life._2;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PolicyStatementDetail_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PolicyStatementDetail_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}PolicyStatementDetailKey" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}PolicyStatementDetailSysKey" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}PolicyStatementDetailName" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}StartDate" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}EndDate" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}TotalGrossPremAmt" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}TotalNetPremAmt" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}TotalAmtWthdrwn" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}LoanBalance" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}TotalIntUnloanedFundAmt" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}TotalIntLoanedFundAmt" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}TotalLoanAmt" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}TotalLoanPaymentAmt" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}TotalLoanIntAmt" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}TotalAdjustmentAmt" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}PolicyValueAtStartDate" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}PolicyValueAtEndDate" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}ExcessDeathBenefitAmt" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}CumMinLevelPremAmt" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}GuarCashValue" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}TotalTermRiderCharge" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}AvgRateOfReturnITD" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}FaceAmt" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}DeathBenefitAmt" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}SurrenderChargeAmt" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}CashSurrValue" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}NetSurrValueAmt" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}TermDivAmt" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}CumMinPremAmt" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}TotCumPremAmt" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}Fee" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}FinancialActivity" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}OLifEExtension" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="DataRep" type="{http://ACORD.org/Standards/Life/2}DATAREP_TYPES" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PolicyStatementDetail_Type", propOrder = {
    "policyStatementDetailKey",
    "policyStatementDetailSysKey",
    "policyStatementDetailName",
    "startDate",
    "endDate",
    "totalGrossPremAmt",
    "totalNetPremAmt",
    "totalAmtWthdrwn",
    "loanBalance",
    "totalIntUnloanedFundAmt",
    "totalIntLoanedFundAmt",
    "totalLoanAmt",
    "totalLoanPaymentAmt",
    "totalLoanIntAmt",
    "totalAdjustmentAmt",
    "policyValueAtStartDate",
    "policyValueAtEndDate",
    "excessDeathBenefitAmt",
    "cumMinLevelPremAmt",
    "guarCashValue",
    "totalTermRiderCharge",
    "avgRateOfReturnITD",
    "faceAmt",
    "deathBenefitAmt",
    "surrenderChargeAmt",
    "cashSurrValue",
    "netSurrValueAmt",
    "termDivAmt",
    "cumMinPremAmt",
    "totCumPremAmt",
    "fee",
    "financialActivity",
    "oLifEExtension"
})
public class PolicyStatementDetailType {

    @XmlElement(name = "PolicyStatementDetailKey")
    protected PERSISTKEY policyStatementDetailKey;
    @XmlElement(name = "PolicyStatementDetailSysKey")
    protected List<SYSKEY> policyStatementDetailSysKey;
    @XmlElement(name = "PolicyStatementDetailName")
    protected String policyStatementDetailName;
    @XmlElement(name = "StartDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar startDate;
    @XmlElement(name = "EndDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar endDate;
    @XmlElement(name = "TotalGrossPremAmt")
    protected BigDecimal totalGrossPremAmt;
    @XmlElement(name = "TotalNetPremAmt")
    protected BigDecimal totalNetPremAmt;
    @XmlElement(name = "TotalAmtWthdrwn")
    protected BigDecimal totalAmtWthdrwn;
    @XmlElement(name = "LoanBalance")
    protected BigDecimal loanBalance;
    @XmlElement(name = "TotalIntUnloanedFundAmt")
    protected BigDecimal totalIntUnloanedFundAmt;
    @XmlElement(name = "TotalIntLoanedFundAmt")
    protected BigDecimal totalIntLoanedFundAmt;
    @XmlElement(name = "TotalLoanAmt")
    protected BigDecimal totalLoanAmt;
    @XmlElement(name = "TotalLoanPaymentAmt")
    protected BigDecimal totalLoanPaymentAmt;
    @XmlElement(name = "TotalLoanIntAmt")
    protected BigDecimal totalLoanIntAmt;
    @XmlElement(name = "TotalAdjustmentAmt")
    protected BigDecimal totalAdjustmentAmt;
    @XmlElement(name = "PolicyValueAtStartDate")
    protected BigDecimal policyValueAtStartDate;
    @XmlElement(name = "PolicyValueAtEndDate")
    protected BigDecimal policyValueAtEndDate;
    @XmlElement(name = "ExcessDeathBenefitAmt")
    protected BigDecimal excessDeathBenefitAmt;
    @XmlElement(name = "CumMinLevelPremAmt")
    protected BigDecimal cumMinLevelPremAmt;
    @XmlElement(name = "GuarCashValue")
    protected BigDecimal guarCashValue;
    @XmlElement(name = "TotalTermRiderCharge")
    protected BigDecimal totalTermRiderCharge;
    @XmlElement(name = "AvgRateOfReturnITD")
    protected Double avgRateOfReturnITD;
    @XmlElement(name = "FaceAmt")
    protected BigDecimal faceAmt;
    @XmlElement(name = "DeathBenefitAmt")
    protected BigDecimal deathBenefitAmt;
    @XmlElement(name = "SurrenderChargeAmt")
    protected BigDecimal surrenderChargeAmt;
    @XmlElement(name = "CashSurrValue")
    protected BigDecimal cashSurrValue;
    @XmlElement(name = "NetSurrValueAmt")
    protected BigDecimal netSurrValueAmt;
    @XmlElement(name = "TermDivAmt")
    protected BigDecimal termDivAmt;
    @XmlElement(name = "CumMinPremAmt")
    protected BigDecimal cumMinPremAmt;
    @XmlElement(name = "TotCumPremAmt")
    protected BigDecimal totCumPremAmt;
    @XmlElement(name = "Fee")
    protected List<FeeType> fee;
    @XmlElement(name = "FinancialActivity")
    protected List<FinancialActivityType> financialActivity;
    @XmlElement(name = "OLifEExtension")
    protected List<OLifEExtensionType> oLifEExtension;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "DataRep")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dataRep;

    /**
     * Gets the value of the policyStatementDetailKey property.
     * 
     * @return
     *     possible object is
     *     {@link PERSISTKEY }
     *     
     */
    public PERSISTKEY getPolicyStatementDetailKey() {
        return policyStatementDetailKey;
    }

    /**
     * Sets the value of the policyStatementDetailKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link PERSISTKEY }
     *     
     */
    public void setPolicyStatementDetailKey(PERSISTKEY value) {
        this.policyStatementDetailKey = value;
    }

    /**
     * Gets the value of the policyStatementDetailSysKey property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the policyStatementDetailSysKey property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPolicyStatementDetailSysKey().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SYSKEY }
     * 
     * 
     */
    public List<SYSKEY> getPolicyStatementDetailSysKey() {
        if (policyStatementDetailSysKey == null) {
            policyStatementDetailSysKey = new ArrayList<SYSKEY>();
        }
        return this.policyStatementDetailSysKey;
    }

    /**
     * Gets the value of the policyStatementDetailName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicyStatementDetailName() {
        return policyStatementDetailName;
    }

    /**
     * Sets the value of the policyStatementDetailName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicyStatementDetailName(String value) {
        this.policyStatementDetailName = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the totalGrossPremAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalGrossPremAmt() {
        return totalGrossPremAmt;
    }

    /**
     * Sets the value of the totalGrossPremAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalGrossPremAmt(BigDecimal value) {
        this.totalGrossPremAmt = value;
    }

    /**
     * Gets the value of the totalNetPremAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalNetPremAmt() {
        return totalNetPremAmt;
    }

    /**
     * Sets the value of the totalNetPremAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalNetPremAmt(BigDecimal value) {
        this.totalNetPremAmt = value;
    }

    /**
     * Gets the value of the totalAmtWthdrwn property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalAmtWthdrwn() {
        return totalAmtWthdrwn;
    }

    /**
     * Sets the value of the totalAmtWthdrwn property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalAmtWthdrwn(BigDecimal value) {
        this.totalAmtWthdrwn = value;
    }

    /**
     * Gets the value of the loanBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLoanBalance() {
        return loanBalance;
    }

    /**
     * Sets the value of the loanBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLoanBalance(BigDecimal value) {
        this.loanBalance = value;
    }

    /**
     * Gets the value of the totalIntUnloanedFundAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalIntUnloanedFundAmt() {
        return totalIntUnloanedFundAmt;
    }

    /**
     * Sets the value of the totalIntUnloanedFundAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalIntUnloanedFundAmt(BigDecimal value) {
        this.totalIntUnloanedFundAmt = value;
    }

    /**
     * Gets the value of the totalIntLoanedFundAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalIntLoanedFundAmt() {
        return totalIntLoanedFundAmt;
    }

    /**
     * Sets the value of the totalIntLoanedFundAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalIntLoanedFundAmt(BigDecimal value) {
        this.totalIntLoanedFundAmt = value;
    }

    /**
     * Gets the value of the totalLoanAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalLoanAmt() {
        return totalLoanAmt;
    }

    /**
     * Sets the value of the totalLoanAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalLoanAmt(BigDecimal value) {
        this.totalLoanAmt = value;
    }

    /**
     * Gets the value of the totalLoanPaymentAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalLoanPaymentAmt() {
        return totalLoanPaymentAmt;
    }

    /**
     * Sets the value of the totalLoanPaymentAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalLoanPaymentAmt(BigDecimal value) {
        this.totalLoanPaymentAmt = value;
    }

    /**
     * Gets the value of the totalLoanIntAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalLoanIntAmt() {
        return totalLoanIntAmt;
    }

    /**
     * Sets the value of the totalLoanIntAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalLoanIntAmt(BigDecimal value) {
        this.totalLoanIntAmt = value;
    }

    /**
     * Gets the value of the totalAdjustmentAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalAdjustmentAmt() {
        return totalAdjustmentAmt;
    }

    /**
     * Sets the value of the totalAdjustmentAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalAdjustmentAmt(BigDecimal value) {
        this.totalAdjustmentAmt = value;
    }

    /**
     * Gets the value of the policyValueAtStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPolicyValueAtStartDate() {
        return policyValueAtStartDate;
    }

    /**
     * Sets the value of the policyValueAtStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPolicyValueAtStartDate(BigDecimal value) {
        this.policyValueAtStartDate = value;
    }

    /**
     * Gets the value of the policyValueAtEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPolicyValueAtEndDate() {
        return policyValueAtEndDate;
    }

    /**
     * Sets the value of the policyValueAtEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPolicyValueAtEndDate(BigDecimal value) {
        this.policyValueAtEndDate = value;
    }

    /**
     * Gets the value of the excessDeathBenefitAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExcessDeathBenefitAmt() {
        return excessDeathBenefitAmt;
    }

    /**
     * Sets the value of the excessDeathBenefitAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExcessDeathBenefitAmt(BigDecimal value) {
        this.excessDeathBenefitAmt = value;
    }

    /**
     * Gets the value of the cumMinLevelPremAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCumMinLevelPremAmt() {
        return cumMinLevelPremAmt;
    }

    /**
     * Sets the value of the cumMinLevelPremAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCumMinLevelPremAmt(BigDecimal value) {
        this.cumMinLevelPremAmt = value;
    }

    /**
     * Gets the value of the guarCashValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGuarCashValue() {
        return guarCashValue;
    }

    /**
     * Sets the value of the guarCashValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGuarCashValue(BigDecimal value) {
        this.guarCashValue = value;
    }

    /**
     * Gets the value of the totalTermRiderCharge property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalTermRiderCharge() {
        return totalTermRiderCharge;
    }

    /**
     * Sets the value of the totalTermRiderCharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalTermRiderCharge(BigDecimal value) {
        this.totalTermRiderCharge = value;
    }

    /**
     * Gets the value of the avgRateOfReturnITD property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAvgRateOfReturnITD() {
        return avgRateOfReturnITD;
    }

    /**
     * Sets the value of the avgRateOfReturnITD property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAvgRateOfReturnITD(Double value) {
        this.avgRateOfReturnITD = value;
    }

    /**
     * Gets the value of the faceAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFaceAmt() {
        return faceAmt;
    }

    /**
     * Sets the value of the faceAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFaceAmt(BigDecimal value) {
        this.faceAmt = value;
    }

    /**
     * Gets the value of the deathBenefitAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDeathBenefitAmt() {
        return deathBenefitAmt;
    }

    /**
     * Sets the value of the deathBenefitAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDeathBenefitAmt(BigDecimal value) {
        this.deathBenefitAmt = value;
    }

    /**
     * Gets the value of the surrenderChargeAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSurrenderChargeAmt() {
        return surrenderChargeAmt;
    }

    /**
     * Sets the value of the surrenderChargeAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSurrenderChargeAmt(BigDecimal value) {
        this.surrenderChargeAmt = value;
    }

    /**
     * Gets the value of the cashSurrValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCashSurrValue() {
        return cashSurrValue;
    }

    /**
     * Sets the value of the cashSurrValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCashSurrValue(BigDecimal value) {
        this.cashSurrValue = value;
    }

    /**
     * Gets the value of the netSurrValueAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNetSurrValueAmt() {
        return netSurrValueAmt;
    }

    /**
     * Sets the value of the netSurrValueAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNetSurrValueAmt(BigDecimal value) {
        this.netSurrValueAmt = value;
    }

    /**
     * Gets the value of the termDivAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTermDivAmt() {
        return termDivAmt;
    }

    /**
     * Sets the value of the termDivAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTermDivAmt(BigDecimal value) {
        this.termDivAmt = value;
    }

    /**
     * Gets the value of the cumMinPremAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCumMinPremAmt() {
        return cumMinPremAmt;
    }

    /**
     * Sets the value of the cumMinPremAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCumMinPremAmt(BigDecimal value) {
        this.cumMinPremAmt = value;
    }

    /**
     * Gets the value of the totCumPremAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotCumPremAmt() {
        return totCumPremAmt;
    }

    /**
     * Sets the value of the totCumPremAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotCumPremAmt(BigDecimal value) {
        this.totCumPremAmt = value;
    }

    /**
     * Gets the value of the fee property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fee property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFee().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FeeType }
     * 
     * 
     */
    public List<FeeType> getFee() {
        if (fee == null) {
            fee = new ArrayList<FeeType>();
        }
        return this.fee;
    }

    /**
     * Gets the value of the financialActivity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the financialActivity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFinancialActivity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FinancialActivityType }
     * 
     * 
     */
    public List<FinancialActivityType> getFinancialActivity() {
        if (financialActivity == null) {
            financialActivity = new ArrayList<FinancialActivityType>();
        }
        return this.financialActivity;
    }

    /**
     * Gets the value of the oLifEExtension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the oLifEExtension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOLifEExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OLifEExtensionType }
     * 
     * 
     */
    public List<OLifEExtensionType> getOLifEExtension() {
        if (oLifEExtension == null) {
            oLifEExtension = new ArrayList<OLifEExtensionType>();
        }
        return this.oLifEExtension;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the dataRep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataRep() {
        return dataRep;
    }

    /**
     * Sets the value of the dataRep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataRep(String value) {
        this.dataRep = value;
    }

}
