//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.13 at 07:49:02 PM IST 
//


package org.acord.standards.life._2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VectorRequest_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VectorRequest_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}VectorSetType" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}VectorItem" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ACORD.org/Standards/Life/2}OLifEExtension" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VectorRequest_Type", propOrder = {
    "vectorSetType",
    "vectorItem",
    "oLifEExtension"
})
public class VectorRequestType {

    @XmlElement(name = "VectorSetType")
    protected TCVECTORSETTYPE vectorSetType;
    @XmlElement(name = "VectorItem")
    protected List<VectorItemType> vectorItem;
    @XmlElement(name = "OLifEExtension")
    protected List<OLifEExtensionType> oLifEExtension;

    /**
     * Gets the value of the vectorSetType property.
     * 
     * @return
     *     possible object is
     *     {@link TCVECTORSETTYPE }
     *     
     */
    public TCVECTORSETTYPE getVectorSetType() {
        return vectorSetType;
    }

    /**
     * Sets the value of the vectorSetType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCVECTORSETTYPE }
     *     
     */
    public void setVectorSetType(TCVECTORSETTYPE value) {
        this.vectorSetType = value;
    }

    /**
     * Gets the value of the vectorItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vectorItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVectorItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VectorItemType }
     * 
     * 
     */
    public List<VectorItemType> getVectorItem() {
        if (vectorItem == null) {
            vectorItem = new ArrayList<VectorItemType>();
        }
        return this.vectorItem;
    }

    /**
     * Gets the value of the oLifEExtension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the oLifEExtension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOLifEExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OLifEExtensionType }
     * 
     * 
     */
    public List<OLifEExtensionType> getOLifEExtension() {
        if (oLifEExtension == null) {
            oLifEExtension = new ArrayList<OLifEExtensionType>();
        }
        return this.oLifEExtension;
    }

}
